=== AdronTech/settlers-remake/resources/buildings/building.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ENTITY % imagelinktype "(SETTLER| GUI| LANDSCAPE)">

<!ENTITY % material "(NO_MATERIAL|
	AXE|
	BOW|
	BLADE|
	BREAD|
	COAL|
	CROP|
	FISH|
	FISHINGROD|
	FLOUR|
	GOLD|
	GOLDORE|
	HAMMER|
	IRON|
	IRONORE|
	MEAT|
	PICK|
	PIG|
	PLANK|
	SAW|
	SCYTHE|
	SPEAR|
	STONE|
	SWORD|
	TRUNK|
	WATER|
	WINE|
	WHITE_BREAD|
	BASKET|
	TREE|
	PLANT)">
<!ENTITY % jobtype "(
	WAIT|
	WALK|
	SHOW|
	HIDE|
	SET_MATERIAL|
	TAKE|
	DROP|
	PRE_SEARCH|
	PRE_SEARCH_IN_AREA|
	FOLLOW_SEARCHED|
	GO_TO|
	LOOK_AT|
	PLAY_ACTION1|
	PLAY_ACTION2|
	EXECUTE|
	AVAILABLE|
	NOT_FULL|
	LOOK_AT_SEARCHED|
	IS_PRODUCTIVE|
	SMOKE_ON|
	SMOKE_OFF|
	START_WORKING|
	STOP_WORKING|
	REMOTETAKE|
	PIG_PLACE|
	PIG_REMOVE|
	PIG_IS_ADULT|
	PIG_IS_THERE|
	POP_TOOL|
	POP_WEAPON|
	DROP_POPPED)
">
<!ENTITY % direction "(EAST| SOUTH_EAST| SOUTH_WEST| WEST | NORTH_WEST | NORTH_EAST)
">

<!ENTITY % searchtype "(FOREIGN_GROUND|
	CUTTABLE_TREE|
	CUTTABLE_STONE|
	PLANTABLE_TREE|
	PLANTABLE_CORN|
	CUTTABLE_CORN|
	FISHABLE|
	RIVER|
	ENEMY)
">
<!ENTITY % groundtype "(
	GRASS|
	DRY_GRASS|
	DESERT|
	EARTH|
	MOUNTAIN|
	SNOW|
	WATER|
	SAND|
	FLATTENED|
	RIVER1|
	RIVER2|
	RIVER3|
	RIVER4|
	MOUNTAINBORDER
)">
<!ELEMENT building (ground+, blocked+, door, stack*, bricklayer+, flag, buildmark*, workcenter?, image*, occupyer*, startjob?, job*, attacker*) >

<!ATTLIST building
   worker CDATA #REQUIRED
   workradius CDATA #IMPLIED
   viewdistance CDATA #IMPLIED
>

<!ELEMENT ground EMPTY>
<!ATTLIST ground
	groundtype %groundtype; #REQUIRED
>

<!ELEMENT workcenter EMPTY>
<!ATTLIST workcenter
   dx CDATA #REQUIRED
   dy CDATA #REQUIRED
>

<!ELEMENT blocked EMPTY>
<!ATTLIST blocked
   dx CDATA #REQUIRED
   dy CDATA #REQUIRED
   block (true|false) "true"
>

<!ELEMENT door EMPTY>
<!ATTLIST door
   dx CDATA #REQUIRED
   dy CDATA #REQUIRED
>

<!ELEMENT flag EMPTY>
<!ATTLIST flag
   dx CDATA #REQUIRED
   dy CDATA #REQUIRED
>


<!ELEMENT stack EMPTY>
<!ATTLIST stack
   dx CDATA #REQUIRED
   dy CDATA #REQUIRED
   buildrequired CDATA #REQUIRED
   material %material; #REQUIRED
>

<!ELEMENT bricklayer EMPTY>
<!ATTLIST bricklayer
   dx CDATA #REQUIRED
   dy CDATA #REQUIRED
   direction %direction; #REQUIRED
>

<!ELEMENT occupyer EMPTY>
<!ATTLIST occupyer
   offsetX CDATA #REQUIRED
   offsetY CDATA #REQUIRED
   type (INFANTARY|BOWMAN) #REQUIRED
   
   soldierX CDATA #REQUIRED
   soldierY CDATA #REQUIRED
   looksRight (true|false) "true" 
>

<!ELEMENT startjob EMPTY>
<!ATTLIST startjob
   name IDREF #REQUIRED
>

<!ELEMENT job EMPTY>
<!ATTLIST job
   name ID #REQUIRED
   type %jobtype; #REQUIRED
   successjob IDREF #REQUIRED
   failjob IDREF #REQUIRED
   dx CDATA #IMPLIED
   dy CDATA #IMPLIED
   time CDATA #IMPLIED
   material %material; #IMPLIED
   direction %direction; #IMPLIED
   search %searchtype; #IMPLIED
>

<!ELEMENT image EMPTY>
<!ATTLIST image
   for (GUI|BUILD|FINAL) #REQUIRED
   type %imagelinktype; #REQUIRED
   file CDATA #REQUIRED
   sequence CDATA #REQUIRED
   image CDATA #REQUIRED
>

<!ELEMENT buildmark EMPTY>
<!ATTLIST buildmark
   dx CDATA #REQUIRED
   dy CDATA #REQUIRED
>

<!ELEMENT attacker EMPTY>
<!ATTLIST attacker
   dx CDATA #REQUIRED
   dy CDATA #REQUIRED
>

=== AdronTech/settlers-remake/src/jsettlers/common/buildings/data/mill.xml
<?xml version="1.1" encoding="UTF-8"?><!DOCTYPE building SYSTEM "building.dtd">

<building worker="MILLER" workradius="10">

	<blocked dx="1" dy="1" />
	<blocked dx="1" dy="3" />
	<blocked dx="1" dy="2" />
	<blocked dx="0" dy="1" />
	<blocked dx="0" dy="2" />
	<blocked dx="-1" dy="1" />
	<blocked dx="-2" dy="0" />
	<blocked dx="-2" dy="-1" />
	<blocked dx="-1" dy="-1" />
	<blocked dx="-1" dy="-2" />
	<blocked dx="0" dy="-1" />
	<blocked dx="1" dy="-1" />
	<blocked dx="1" dy="0" />
	<blocked dx="0" dy="-2" />
	<blocked dx="0" dy="0" />
	<blocked dx="-1" dy="0" />
	<door dx="-1" dy="2" />
	
	<stack dx="2" dy="2" material="CROP" buildrequired="0" />
	<stack dx="0" dy="3" material="PLANK" buildrequired="6" />
	<stack dx="2" dy="3" material="STONE" buildrequired="3" />
		
	<bricklayer dx="-2" dy="1" direction="NORTH_EAST"/>
	<bricklayer dx="0" dy="3" direction="NORTH_EAST"/>
	<bricklayer dx="2" dy="3" direction="NORTH_WEST"/>
	<bricklayer dx="2" dy="2" direction="NORTH_WEST"/>
	<bricklayer dx="3" dy="1" direction="NORTH_WEST"/>
	
	<flag dx="-5" dy="-10" />
	
	<startjob name="gohome"/>
	
	<!-- going home job -->
	<job name="gohome" 		type="GO_TO" 			successjob="hide" 			failjob="waithome" 	dx="-1" dy="2"/>
	<job name="waithome" 	type="WAIT" 			successjob="gohome" 		failjob="waithome" 	time="3"/>
	<job name="hide" 		type="HIDE" 			successjob="start" 			failjob="start"		/>
	
	<job name="start" 		type="WAIT" 			successjob="checkflour" 	failjob="show" 		time="3.0"/>
	<job name="checkflour" 	type="NOT_FULL" 		successjob="checkcrop" 		failjob="hide" 		dx="-2" dy="1" material="FLOUR"/>
	<job name="checkcrop"	type="AVAILABLE"		successjob="show"			failjob="start"		dx="2" dy="2" material="CROP"/>	
	<job name="show"		type="SHOW"				successjob="go_to_crop"		failjob="hide"		dx="-1" dy="2"/>
	<job name="go_to_crop"	type="GO_TO"			successjob="take"			failjob="gohome"	dx="2" dy="2"/>
	<job name="changeMat1"	type="SET_MATERIAL"		successjob="go_back"		failjob="gohome"	material="CROP"/>
	<job name="take"		type="TAKE"				successjob="changeMat1"		failjob="gohome"	material="CROP"/>
	<job name="go_back"		type="GO_TO"			successjob="hide1"			failjob="gohome"	dx="-1" dy="2"/>
	<job name="hide1"		type="HIDE"				successjob="makeflour"		failjob="start"		/>
	<job name="makeflour"	type="WAIT"				successjob="changeMat2"		failjob="start"		time="2.0"/>
	<job name="changeMat2"	type="SET_MATERIAL"		successjob="get_flour"		failjob="hide"		material="FLOUR"/>
	<job name="get_flour"	type="GO_TO"			successjob="look"			failjob="gohome"	dx="-2" dy="1"/>
	<job name="look"		type="LOOK_AT"			successjob="drop"			failjob="hide"		direction="NORTH_EAST"/>
	<job name="drop"		type="DROP"				successjob="changeMat3"		failjob="gohome"	material="FLOUR"/>
	<job name="changeMat3"	type="SET_MATERIAL"		successjob="gohome"			failjob="gohome"	material="NO_MATERIAL"/>
  
</building>

=== AdronTech/settlers-remake/jsettlers.common/resources/buildings/winegrower.xml
<?xml version="1.1" encoding="UTF-8"?>
<!DOCTYPE building SYSTEM "building.dtd">
<building worker="WINEGROWER" workradius="4">
	<ground groundtype="GRASS"/>
	<ground groundtype="EARTH"/>
	<ground groundtype="FLATTENED"/>
	
 	<blocked dx="-3" dy="0" block="true" />
	<blocked dx="-3" dy="-1" block="true" />
	<blocked dx="-2" dy="-2" block="true" />
	<blocked dx="-3" dy="-3" block="true" />
	<blocked dx="-1" dy="-3" block="true" />
	<blocked dx="1" dy="-1" block="true" />
	<blocked dx="2" dy="1" block="true" />
	<blocked dx="2" dy="2" block="true" />
	<blocked dx="1" dy="0" block="true" />
	<blocked dx="1" dy="1" block="true" />
	<blocked dx="1" dy="2" block="true" />
	<blocked dx="0" dy="-2" block="true" />
	<blocked dx="0" dy="-1" block="true" />
	<blocked dx="0" dy="0" block="true" />
	<blocked dx="0" dy="1" block="true" />
	<blocked dx="0" dy="2" block="true" />
	<blocked dx="-1" dy="-2" block="true" />
	<blocked dx="-1" dy="-1" block="true" />
	<blocked dx="-1" dy="0" block="true" />
	<blocked dx="-1" dy="1" block="true" />
	<blocked dx="-2" dy="-1" block="true" />
	<blocked dx="-2" dy="0" block="true" />
	<blocked dx="-2" dy="1" block="true" />
	<blocked dx="-2" dy="-3" block="true" />
	<blocked dx="2" dy="0" block="true" />
	<blocked dx="0" dy="3" block="true" />
	<blocked dx="-3" dy="-2" block="true" />
	<blocked dx="-1" dy="2" block="false" />
	<blocked dx="2" dy="4" block="false" />
	<blocked dx="1" dy="-2" block="false" />
	<blocked dx="1" dy="3" block="false" />
	<blocked dx="2" dy="3" block="false" />
	<blocked dx="3" dy="3" block="false" />
	<blocked dx="3" dy="2" block="false" />
	<blocked dx="3" dy="1" block="false" />
	<blocked dx="2" dy="-1" block="false" />
	<blocked dx="3" dy="0" block="false" />
	<blocked dx="3" dy="4" block="false" />
	<blocked dx="0" dy="4" block="false" />
	<blocked dx="-1" dy="3" block="false" />
	<blocked dx="-2" dy="2" block="false" />
	<blocked dx="-3" dy="1" block="false" />
	<blocked dx="-4" dy="0" block="false" />
	<blocked dx="-4" dy="-1" block="false" />
	<blocked dx="-4" dy="-2" block="false" />
	<blocked dx="-4" dy="-3" block="false" />
	<blocked dx="-4" dy="-4" block="false" />
	<blocked dx="-3" dy="-4" block="false" />
	<blocked dx="-2" dy="-4" block="false" />
	<blocked dx="-1" dy="-4" block="false" />
	<blocked dx="0" dy="-3" block="false" />
	<blocked dx="1" dy="4" block="false" />
	
	<door dx="-1" dy="2" />
	
    <!-- materials checked with original -->
	<stack dx="0" dy="4" material="PLANK" buildrequired="4" />
	<stack dx="2" dy="4" material="STONE" buildrequired="4" />
	
	<bricklayer dx="2" dy="3" direction="NORTH_WEST" />
	<bricklayer dx="3" dy="2" direction="NORTH_WEST" />
	<bricklayer dx="-3" dy="1" direction="NORTH_EAST" />
	<bricklayer dx="-1" dy="3" direction="NORTH_EAST" />
	
	<flag dx="-1" dy="0" />
	
	<buildmark dx="-3" dy="0" />
	<buildmark dx="0" dy="3" />
	<buildmark dx="2" dy="2" />
	<buildmark dx="2" dy="0" />
	<buildmark dx="-1" dy="-3" />
	<buildmark dx="-3" dy="-3" />

	<workcenter dx="3" dy="9"/>

	<image file="14" for="GUI" type="GUI" sequence="90" image="0"/>
    <image file="13" type="SETTLER" for="FINAL" image="0" sequence="33"/>
    <image file="13" type="SETTLER" for="BUILD" image="1" sequence="33"/>
	
	<startjob name="gohome"/>	
	
	<!-- going home job -->
	<job name="gohome" 			type="GO_TO" 			successjob="hide" 			failjob="hide" 		dx="-1" dy="2"/>
	<job name="hide" 			type="HIDE" 			successjob="start" 			failjob="start"			/>
	
	<job name="start" 			type="WAIT" 			successjob="check" 			failjob="check" 		time="8.0"/>
    <job name="check"			type="NOT_FULL"			successjob="presearch1"		failjob="presearch2"	dx="3" dy="4" material="WINE"/>
    
	<job name="presearch1" 		type="PRE_SEARCH" 		successjob="goHarvesting1" 	failjob="presearch2" 	search="HARVESTABLE_WINE"/>
	<job name="presearch2" 		type="PRE_SEARCH" 		successjob="goPlanting1"	failjob="start" 		search="PLANTABLE_WINE"/>
        
    <!-- 1: harvest some wine -->
    <job name="goHarvesting1"	type="SET_MATERIAL"		successjob="goHarvesting2"	failjob="gohome"		material="BASKET"/>
    <job name="goHarvesting2"	type="SHOW"				successjob="search1"		failjob="start"			dx="-1" dy="4" direction="SOUTH_WEST"/>
    <job name="search1"  		type="FOLLOW_SEARCHED"	successjob="cutlook_at_NE"	failjob="hide"			/>
   
    <job name="cutlook_at_NE"	type="LOOK_AT"			successjob="cut1"			failjob="gohome"		direction="NORTH_EAST"/>
    <job name="cut1"			type="PLAY_ACTION1"		successjob="cutlook_at_SW"	failjob="gohome"		time="1.0"/>
    <job name="cutlook_at_SW"	type="LOOK_AT"			successjob="cut2"			failjob="gohome"		direction="SOUTH_WEST"/>
    <job name="cut2"			type="PLAY_ACTION1"		successjob="cutlook_at_W"	failjob="gohome"		time="1.0"/>
    <job name="cutlook_at_W" 	type="LOOK_AT"			successjob="cut3"			failjob="gohome"		direction="WEST"/>
    <job name="cut3"			type="PLAY_ACTION1"		successjob="cutlook_at_NW"	failjob="gohome"		time="1.0"/>
    <job name="cutlook_at_NW" 	type="LOOK_AT"			successjob="cut4"			failjob="gohome"		direction="NORTH_WEST"/>
    <job name="cut4"			type="PLAY_ACTION1"		successjob="execute1"		failjob="gohome"		time="1.0"/>
    
    <job name="execute1"		type="EXECUTE"			successjob="look_at"		failjob="gohome"		search="HARVESTABLE_WINE"/>
    <job name="look_at"			type="LOOK_AT"			successjob="take"			failjob="gohome"		direction="NORTH_EAST"/>
    <job name="take" 			type="TAKE" 			successjob="changeMat2" 	failjob="gohome"		material="WINE"/>
	<job name="changeMat2"	 	type="SET_MATERIAL" 	successjob="goback" 		failjob="gohome" 		material="WINE"/>
	<job name="goback" 			type="GO_TO" 			successjob="produceWine1" 	failjob="produceWine1"	dx="-1" dy="2"/>
	
	<job name="produceWine1"	type="HIDE" 			successjob="produceWine2" 	failjob="hide" 			/>
	<job name="produceWine2"	type="WAIT" 			successjob="produceWine3" 	failjob="hide" 			time="3.0"/>
	<job name="produceWine3"	type="SHOW" 			successjob="goToDrop"		failjob="hide" 			dx="-1" dy="4" direction="SOUTH_WEST"/>
	
	<job name="goToDrop"		type="GO_TO" 			successjob="look"			failjob="hide" 			dx="3" dy="4"/>
	<job name="look"			type="LOOK_AT"			successjob="drop"			failjob="hide"			direction="NORTH_EAST"/>
	<job name="drop" 			type="DROP" 			successjob="changeMat" 		failjob="hide" 			material="WINE"/>
	<job name="changeMat" 		type="SET_MATERIAL"		successjob="gohome" 		failjob="hide" 			material="NO_MATERIAL"/>
	
     <!-- 2: plant a new corn -->
    <job name="goPlanting1"		type="SET_MATERIAL"		successjob="goPlantingShow"	failjob="gohome"		material="PLANT"/>
    <job name="goPlantingShow"	type="SHOW"				successjob="search2"		failjob="hide"			dx="-1" dy="4" direction="SOUTH_WEST"/>
    <job name="search2"			type="FOLLOW_SEARCHED"	successjob="seedlook_at_NE"	failjob="gohome"		/>
    <job name="seedlook_at_NE"	type="LOOK_AT"			successjob="seed1"			failjob="gohome"		direction="NORTH_EAST"/>
    <job name="seed1"			type="PLAY_ACTION2"		successjob="seedlook_at_SE"	failjob="gohome"		time="1.4"/>
	<job name="seedlook_at_SE"	type="LOOK_AT"			successjob="seed2"			failjob="gohome"		direction="SOUTH_EAST"/>
    <job name="seed2"			type="PLAY_ACTION2"		successjob="seedlook_at_SW"	failjob="gohome"		time="1.4"/>
	<job name="seedlook_at_SW"	type="LOOK_AT"			successjob="seed3"			failjob="gohome"		direction="SOUTH_WEST"/>
    <job name="seed3"			type="PLAY_ACTION2"		successjob="seedlook_at_NW"	failjob="gohome"		time="1.4"/>
	<job name="seedlook_at_NW"	type="LOOK_AT"			successjob="seed4"			failjob="gohome"		direction="NORTH_WEST"/>
    <job name="seed4"			type="PLAY_ACTION2"		successjob="execute2"		failjob="gohome"		time="1.4"/>
	<job name="execute2"		type="EXECUTE"			successjob="no_mat2"		failjob="gohome"		search="PLANTABLE_WINE"/>
 	<job name="no_mat2" 		type="SET_MATERIAL"		successjob="gohome" 		failjob="gohome" 		material="NO_MATERIAL"/>
 	
 </building>

=== AdronTech/settlers-remake/jsettlers.common/resources/buildings/coalmine.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE building SYSTEM "building.dtd">
<building worker="MINER" workradius="0">
    <ground groundtype="MOUNTAIN" />

    <blocked dx="1" dy="3" block="true" />
    <blocked dx="1" dy="2" block="true" />
    <blocked dx="2" dy="2" block="true" />
    <blocked dx="2" dy="1" block="true" />
    <blocked dx="2" dy="0" block="true" />
    <blocked dx="1" dy="1" block="true" />
    <blocked dx="1" dy="0" block="true" />
    <blocked dx="1" dy="-1" block="true" />
    <blocked dx="0" dy="-2" block="true" />
    <blocked dx="0" dy="-1" block="true" />
    <blocked dx="0" dy="0" block="true" />
    <blocked dx="0" dy="1" block="true" />
    <blocked dx="0" dy="2" block="true" />
    <blocked dx="-2" dy="0" block="true" />
    <blocked dx="-3" dy="-1" block="true" />
    <blocked dx="-1" dy="0" block="true" />
    <blocked dx="-2" dy="-1" block="true" />
    <blocked dx="-3" dy="-2" block="true" />
    <blocked dx="-3" dy="-3" block="true" />
    <blocked dx="-3" dy="-4" block="true" />
    <blocked dx="-2" dy="-3" block="true" />
    <blocked dx="-2" dy="-4" block="true" />
    <blocked dx="-2" dy="-2" block="true" />
    <blocked dx="-1" dy="-1" block="true" />
    <blocked dx="-1" dy="-2" block="true" />
    <blocked dx="-1" dy="-3" block="true" />
    <blocked dx="-1" dy="1" block="false" />
    <blocked dx="-2" dy="1" block="false" />
    <blocked dx="-3" dy="0" block="false" />
    <blocked dx="-1" dy="2" block="false" />
    <blocked dx="0" dy="3" block="false" />
    <blocked dx="1" dy="4" block="false" />
    <blocked dx="2" dy="4" block="false" />
    <blocked dx="2" dy="3" block="false" />
    <blocked dx="3" dy="3" block="false" />
    <blocked dx="3" dy="2" block="false" />
    <blocked dx="3" dy="1" block="false" />
    <blocked dx="3" dy="0" block="false" />
    <blocked dx="2" dy="-1" block="false" />
    <blocked dx="1" dy="-2" block="false" />
    <blocked dx="0" dy="-3" block="false" />
    <blocked dx="-1" dy="-4" block="false" />
    <blocked dx="-2" dy="-5" block="false" />
    <blocked dx="-3" dy="-5" block="false" />
    <blocked dx="-4" dy="-5" block="false" />
    <blocked dx="-4" dy="-4" block="false" />
    <blocked dx="-4" dy="-3" block="false" />
    <blocked dx="-4" dy="-2" block="false" />
    <blocked dx="-4" dy="-1" block="false" />
    <blocked dx="-3" dy="1" block="false" />
    <blocked dx="-2" dy="2" block="false" />
    <blocked dx="-1" dy="3" block="false" />
    <blocked dx="0" dy="4" block="false" />
    <blocked dx="1" dy="5" block="false" />
    <door dx="-1" dy="1" />
    <!-- materials checked with original -->
    <stack dx="-2" dy="2" material="PLANK" buildrequired="4" />
    <stack dx="1" dy="4" material="STONE" buildrequired="1" />
    <stack dx="2" dy="4" material="FISH" buildrequired="0" />
    <stack dx="3" dy="3" material="MEAT" buildrequired="0" />
    <stack dx="3" dy="1" material="BREAD" buildrequired="0" />
    <bricklayer dx="-2" dy="1" direction="NORTH_EAST" />
    <bricklayer dx="0" dy="3" direction="NORTH_EAST" />
    <bricklayer dx="2" dy="3" direction="NORTH_WEST" />
    <bricklayer dx="3" dy="2" direction="NORTH_WEST" />
    <flag dx="-3" dy="-5" />
    <buildmark dx="1" dy="3" />
    <buildmark dx="2" dy="0" />
    <buildmark dx="-2" dy="-4" />
    <buildmark dx="-3" dy="-1" />
    <image file="14" for="GUI" type="GUI" sequence="51" image="0" />
    <image file="13" for="FINAL" type="SETTLER" sequence="6" image="0" />
    <image file="13" for="BUILD" type="SETTLER" sequence="6" image="1" />

    <!-- going home job -->
    <startjob name="gohome" />
    <job name="gohome" type="GO_TO" successjob="hide" failjob="hide" dx="-1" dy="1" />

    <job name="hide" type="HIDE" successjob="A_wait" failjob="A_wait" />

    <!-- Wait for BREAD -->
    <job name="A_wait" type="WAIT" successjob="A_checkore" failjob="A_checkore" time="3" />
    <job name="A_checkore" type="NOT_FULL" successjob="A_checkfood" failjob="B_wait" dx="-1" dy="3" material="COAL" />
    <job name="A_checkfood" type="AVAILABLE" successjob="mine_bread" failjob="B_wait" dx="3" dy="1" material="BREAD" />

    <!-- Wait some more for BREAD -->
    <job name="B_wait" type="WAIT" successjob="B_checkore" failjob="B_checkore" time="5" />
    <job name="B_checkore" type="NOT_FULL" successjob="B_checkfood" failjob="C_wait" dx="-1" dy="3" material="COAL" />
    <job name="B_checkfood" type="AVAILABLE" successjob="mine_bread" failjob="C_wait" dx="3" dy="1" material="BREAD" />

    <!-- Wait for MEAT -->
    <job name="C_wait" type="WAIT" successjob="C_checkore" failjob="C_checkore" time="7" />
    <job name="C_checkore" type="NOT_FULL" successjob="C_checkfood1" failjob="D_wait" dx="-1" dy="3" material="COAL" />
    <job name="C_checkfood1" type="AVAILABLE" successjob="mine_bread" failjob="C_checkfood2" dx="3" dy="1" material="BREAD" />
    <job name="C_checkfood2" type="AVAILABLE" successjob="mine_meat" failjob="D_wait" dx="3" dy="3" material="MEAT" />

    <!-- Wait for FISH -->
    <job name="D_wait" type="WAIT" successjob="D_checkore" failjob="D_checkore" time="6" />
    <job name="D_checkore" type="NOT_FULL" successjob="D_checkfood1" failjob="E_wait" dx="-1" dy="3" material="COAL" />
    <job name="D_checkfood1" type="AVAILABLE" successjob="mine_bread" failjob="D_checkfood2" dx="3" dy="1" material="BREAD" />
    <job name="D_checkfood2" type="AVAILABLE" successjob="mine_meat" failjob="D_checkfood3" dx="3" dy="3" material="MEAT" />
    <job name="D_checkfood3" type="AVAILABLE" successjob="mine_fish" failjob="E_wait" dx="2" dy="4" material="FISH" />

    <!-- Wait for FISH -->
    <job name="E_wait" type="WAIT" successjob="E_checkore" failjob="E_checkore" time="5" />

    <job name="E_checkore" type="NOT_FULL" successjob="E_checkfood1" failjob="E_wait" dx="-1" dy="3" material="COAL" />
    <job name="E_checkfood1" type="AVAILABLE" successjob="mine_bread" failjob="E_checkfood2" dx="3" dy="1" material="BREAD" />
    <job name="E_checkfood2" type="AVAILABLE" successjob="mine_meat" failjob="E_checkfood3" dx="3" dy="3" material="MEAT" />
    <job name="E_checkfood3" type="AVAILABLE" successjob="mine_fish" failjob="E_wait" dx="2" dy="4" material="FISH" />


    <job name="mine_meat" type="REMOTETAKE" successjob="mine" failjob="E_wait" material="MEAT" dx="3" dy="3" />
    <job name="mine_bread" type="REMOTETAKE" successjob="mine" failjob="E_wait" material="BREAD"  dx="3" dy="1" />
    <job name="mine_fish" type="REMOTETAKE" successjob="mine" failjob="E_wait" material="FISH" dx="2" dy="4" />

    <job name="mine" type="IS_PRODUCTIVE" successjob="successful" failjob="noore1" />

    <!-- successful mining -->
    <job name="successful" type="SET_MATERIAL" successjob="show_full" failjob="gohome" material="COAL" />
    <job name="show_full" type="SHOW" successjob="successful1" failjob="gohome" dx="-1" dy="1" />
    <job name="successful1" type="WALK" successjob="successful2" failjob="gohome" direction="SOUTH_WEST" />
    <job name="successful2" type="WALK" successjob="successful3" failjob="gohome" direction="SOUTH_WEST" />
    <job name="successful3" type="LOOK_AT" successjob="successful4" failjob="gohome" direction="SOUTH_WEST" />
    <job name="successful4" type="DROP" successjob="successful7" failjob="gohome" material="COAL" />
    <job name="successful7" type="WALK" successjob="successful8" failjob="gohome" direction="NORTH_EAST" />
    <job name="successful8" type="WALK" successjob="hide" failjob="hide" direction="NORTH_EAST" />

    <!-- failed mining -->
    <job name="noore1" type="SET_MATERIAL" successjob="noore2" failjob="gohome" material="BASKET" />
    <job name="noore2" type="SHOW" successjob="noore4" failjob="gohome" dx="-1" dy="1" />
    <job name="noore4" type="WALK" successjob="noore5" failjob="gohome" direction="SOUTH_WEST" />
    <job name="noore5" type="LOOK_AT" successjob="noore6" failjob="gohome" direction="SOUTH_WEST" />
    <job name="noore6" type="PLAY_ACTION1" successjob="noore7" failjob="gohome" time="3.5" />
    <job name="noore7" type="WALK" successjob="hide" failjob="hide" direction="NORTH_EAST" />
</building>

=== AdronTech/settlers-remake/resources/buildings/coalmine.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE building SYSTEM "building.dtd">
<building worker="MINER" workradius="0">
	<ground groundtype="MOUNTAIN" />

	<blocked dx="-2" dy="0" block="true" />
	<blocked dx="-2" dy="-1" block="true" />
	<blocked dx="-2" dy="-2" block="true" />
	<blocked dx="-1" dy="1" block="true" />
	<blocked dx="-1" dy="0" block="true" />
	<blocked dx="-1" dy="-2" block="true" />
	<blocked dx="-1" dy="-3" block="true" />
	<blocked dx="0" dy="-2" block="true" />
	<blocked dx="0" dy="-1" block="true" />
	<blocked dx="0" dy="0" block="true" />
	<blocked dx="0" dy="1" block="true" />
	<blocked dx="0" dy="2" block="true" />
	<blocked dx="1" dy="3" block="true" />
	<blocked dx="1" dy="2" block="true" />
	<blocked dx="1" dy="1" block="true" />
	<blocked dx="1" dy="0" block="true" />
	<blocked dx="1" dy="-1" block="true" />
	<blocked dx="2" dy="0" block="true" />
	<blocked dx="2" dy="1" block="true" />
	<blocked dx="-2" dy="1" block="true" />
	<blocked dx="3" dy="2" block="false" />
	<blocked dx="3" dy="3" block="false" />
	<blocked dx="2" dy="2" block="false" />
	<blocked dx="2" dy="3" block="false" />
	<blocked dx="2" dy="4" block="false" />
	<blocked dx="1" dy="4" block="false" />
	<blocked dx="0" dy="3" block="false" />
	<blocked dx="-1" dy="2" block="false" />
	<blocked dx="-3" dy="0" block="false" />
	<blocked dx="-3" dy="-1" block="false" />
	<blocked dx="-3" dy="-2" block="false" />
	<blocked dx="-3" dy="-3" block="false" />
	<blocked dx="-2" dy="-3" block="false" />
	<blocked dx="-2" dy="-4" block="false" />
	<blocked dx="-1" dy="-4" block="false" />
	<blocked dx="0" dy="-3" block="false" />
	<blocked dx="1" dy="-2" block="false" />
	<blocked dx="2" dy="-1" block="false" />
	<blocked dx="3" dy="0" block="false" />
	<blocked dx="3" dy="1" block="false" />
	<blocked dx="4" dy="1" block="false" />
	<blocked dx="4" dy="2" block="false" />
	<blocked dx="4" dy="3" block="false" />
	<blocked dx="-3" dy="1" block="false" />
	<blocked dx="-2" dy="2" block="false" />
	<blocked dx="-1" dy="3" block="false" />
	<blocked dx="0" dy="4" block="false" />
	<door dx="-1" dy="2" />
	<stack dx="0" dy="4" material="PLANK" buildrequired="3" />
	<stack dx="2" dy="4" material="STONE" buildrequired="1" />
	<bricklayer dx="-2" dy="2" direction="NORTH_EAST" />
	<bricklayer dx="0" dy="3" direction="NORTH_EAST" />
	<bricklayer dx="2" dy="3" direction="NORTH_WEST" />
	<bricklayer dx="3" dy="2" direction="NORTH_WEST" />
	<flag dx="-1" dy="0" />
	<buildmark dx="1" dy="3" />
	<buildmark dx="2" dy="0" />
	<buildmark dx="-1" dy="-3" />
	<buildmark dx="-2" dy="1" />
	<buildmark dx="-2" dy="-2" />
</building>

=== AdronTech/settlers-remake/src/jsettlers/common/buildings/data/fisher.xml
<!DOCTYPE building SYSTEM "building.dtd">
<building worker="FISHERMAN" workradius="30">
	<blocked dx="-1" dy="1" block="true" />
	<blocked dx="-1" dy="0" block="true" />
	<blocked dx="-1" dy="-1" block="true" />
	<blocked dx="-1" dy="-2" block="true" />
	<blocked dx="0" dy="-2" block="true" />
	<blocked dx="1" dy="-1" block="true" />
	<blocked dx="2" dy="2" block="true" />
	<blocked dx="1" dy="1" block="true" />
	<blocked dx="1" dy="0" block="true" />
	<blocked dx="0" dy="-1" block="true" />
	<blocked dx="0" dy="0" block="true" />
	<blocked dx="0" dy="1" block="true" />
	<blocked dx="0" dy="2" block="true" />
	<blocked dx="1" dy="3" block="true" />
	<blocked dx="1" dy="2" block="true" />
	<blocked dx="2" dy="3" block="true" />
	<blocked dx="2" dy="0" block="true" />
	<blocked dx="-1" dy="2" block="true" />
	<blocked dx="2" dy="1" block="false" />
	<blocked dx="0" dy="3" block="false" />
	<blocked dx="1" dy="4" block="false" />
	<blocked dx="2" dy="4" block="false" />
	<blocked dx="3" dy="4" block="false" />
	<blocked dx="3" dy="3" block="false" />
	<blocked dx="3" dy="2" block="false" />
	<blocked dx="3" dy="1" block="false" />
	<blocked dx="-1" dy="-3" block="false" />
	<blocked dx="0" dy="-3" block="false" />
	<blocked dx="2" dy="-1" block="false" />
	<blocked dx="3" dy="0" block="false" />
	<blocked dx="-2" dy="-3" block="false" />
	<blocked dx="-2" dy="-2" block="false" />
	<blocked dx="-2" dy="-1" block="false" />
	<blocked dx="-2" dy="0" block="false" />
	<blocked dx="-2" dy="1" block="false" />
	<blocked dx="-1" dy="3" block="false" />
	<blocked dx="0" dy="4" block="false" />
	<blocked dx="1" dy="-2" block="false" />
	<door dx="2" dy="1" />
	<stack dx="1" dy="4" material="STONE" buildrequired="2" />
	<stack dx="3" dy="4" material="PLANK" buildrequired="4" />
	<bricklayer dx="3" dy="2" direction="NORTH_WEST" />
	<bricklayer dx="3" dy="3" direction="NORTH_WEST" />
	<bricklayer dx="0" dy="3" direction="NORTH_WEST" />
	<bricklayer dx="1" dy="4" direction="NORTH_EAST" />
	<flag dx="1" dy="-2" />
	<buildmark dx="-1" dy="2" />
	<buildmark dx="-1" dy="0" />
	<buildmark dx="-1" dy="-2" />
	<buildmark dx="2" dy="0" />
	<buildmark dx="2" dy="3" />
	
	<startjob name="gohome"/>

	<!-- go home -->
	<job name="gohome" 			type="GO_TO" 			successjob="hide" 			failjob="gohome_wait" 	dx="2" dy="1"/>
	<!-- go home failed, retry -->
	<job name="gohome_wait" 	type="WAIT" 			successjob="gohome" 		failjob="gohome_wait" 	time="1.0"/>
	
	<!-- arrive at front door => hide -->
	<job name="hide" 			type="HIDE" 			successjob="reset" 			failjob="gohome_wait"/>
	<job name="reset" 			type="SET_MATERIAL"		successjob="wait_at_home" 	failjob="wait_at_home" 	material="NO_MATERIAL"/>
	
	<!-- wait some time -->
	<job name="wait_at_home" 	type="WAIT" 			successjob="check" 			failjob="wait_at_home" 	time="1.0"/>
	
	<job name="check" 			type="NOT_FULL" 		successjob="presearch" 		failjob="hide" 			dx="3" dy="4" material="FISH"/>
	
	<!-- show -->
	<job name="presearch" 		type="PRE_SEARCH_IN_AREA" 		successjob="show" 			failjob="wait_at_home" 	search="FISHABLE"/>
	<job name="show" 			type="SHOW" 			successjob="search_fish" 	failjob="hide" 			dx="2" dy="1"/>
	
	<!-- go search -->
	<job name="search_fish" 	type="FOLLOW_SEARCHED" 	successjob="look_at_fish" 	failjob="gohome" 		/>
	
	<!-- fish it -->
	<job name="look_at_fish" 	type="LOOK_AT" 			successjob="play" 	failjob="gohome" 		direction="NORTH_WEST"/>
	<job name="play" 			type="PLAY_ACTION2" 	successjob="successful" 	failjob="gohome" 		time="1"/>
	<job name="successful"		type="IS_PRODUCTIVE"	successjob="play_success1" failjob="play_fail"/>
	
	<!--  fail -->
	<job name="play_fail" 		type="PLAY_ACTION1" 	successjob="gohome" 	failjob="gohome" 		time="2"/>
	
	<!-- success -->	
	<job name="play_success1"	type="SET_MATERIAL" 	successjob="play_success2" 	failjob="gohome" 		material="FISH"/>
	<job name="play_success2" 		type="PLAY_ACTION1" 	successjob="go_drop" 	failjob="gohome" 		time="2"/>
	
	<!-- drop it at (3|4) -->
	<job name="go_drop"			type="GO_TO" 			successjob="drop1" 	failjob="gohome" 	dx="3" dy="4"/>
	<job name="drop1" 			type="DROP" 			successjob="drop2" 	failjob="gohome" 	material="STONE"/>
	<job name="drop2" 			type="SET_MATERIAL" 	successjob="drop3" 	failjob="gohome" 		material="NO_MATERIAL"/>
	<job name="drop3" 			type="TAKE" 			successjob="walk1" 	failjob="gohome" 	material="NO_MATERIAL"/>
	
	<job name="walk1" 			type="WALK" 			successjob="walk2" 			failjob="hide" 			direction="NORTH_EAST"/>
	<job name="walk2" 			type="WALK" 			successjob="walk3" 			failjob="hide" 			direction="NORTH_EAST"/>
	<job name="walk3" 			type="WALK" 			successjob="hide" 			failjob="hide" 			direction="NORTH_WEST"/>
	
</building>
