=== AdronTech/settlers-remake/resources/buildings/building.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ENTITY % imagelinktype "(SETTLER| GUI| LANDSCAPE)">

<!ENTITY % material "(NO_MATERIAL|
	AXE|
	BOW|
	BLADE|
	BREAD|
	COAL|
	CROP|
	FISH|
	FISHINGROD|
	FLOUR|
	GOLD|
	GOLDORE|
	HAMMER|
	IRON|
	IRONORE|
	MEAT|
	PICK|
	PIG|
	PLANK|
	SAW|
	SCYTHE|
	SPEAR|
	STONE|
	SWORD|
	TRUNK|
	WATER|
	WINE|
	WHITE_BREAD|
	BASKET|
	TREE|
	PLANT)">
<!ENTITY % jobtype "(
	WAIT|
	WALK|
	SHOW|
	HIDE|
	SET_MATERIAL|
	TAKE|
	DROP|
	PRE_SEARCH|
	PRE_SEARCH_IN_AREA|
	FOLLOW_SEARCHED|
	GO_TO|
	LOOK_AT|
	PLAY_ACTION1|
	PLAY_ACTION2|
	EXECUTE|
	AVAILABLE|
	NOT_FULL|
	LOOK_AT_SEARCHED|
	IS_PRODUCTIVE|
	SMOKE_ON|
	SMOKE_OFF|
	START_WORKING|
	STOP_WORKING|
	REMOTETAKE|
	PIG_PLACE|
	PIG_REMOVE|
	PIG_IS_ADULT|
	PIG_IS_THERE|
	POP_TOOL|
	POP_WEAPON|
	DROP_POPPED)
">
<!ENTITY % direction "(EAST| SOUTH_EAST| SOUTH_WEST| WEST | NORTH_WEST | NORTH_EAST)
">

<!ENTITY % searchtype "(FOREIGN_GROUND|
	CUTTABLE_TREE|
	CUTTABLE_STONE|
	PLANTABLE_TREE|
	PLANTABLE_CORN|
	CUTTABLE_CORN|
	FISHABLE|
	RIVER|
	ENEMY)
">
<!ENTITY % groundtype "(
	GRASS|
	DRY_GRASS|
	DESERT|
	EARTH|
	MOUNTAIN|
	SNOW|
	WATER|
	SAND|
	FLATTENED|
	RIVER1|
	RIVER2|
	RIVER3|
	RIVER4|
	MOUNTAINBORDER
)">
<!ELEMENT building (ground+, blocked+, door, stack*, bricklayer+, flag, buildmark*, workcenter?, image*, occupyer*, startjob?, job*, attacker*) >

<!ATTLIST building
   worker CDATA #REQUIRED
   workradius CDATA #IMPLIED
   viewdistance CDATA #IMPLIED
>

<!ELEMENT ground EMPTY>
<!ATTLIST ground
	groundtype %groundtype; #REQUIRED
>

<!ELEMENT workcenter EMPTY>
<!ATTLIST workcenter
   dx CDATA #REQUIRED
   dy CDATA #REQUIRED
>

<!ELEMENT blocked EMPTY>
<!ATTLIST blocked
   dx CDATA #REQUIRED
   dy CDATA #REQUIRED
   block (true|false) "true"
>

<!ELEMENT door EMPTY>
<!ATTLIST door
   dx CDATA #REQUIRED
   dy CDATA #REQUIRED
>

<!ELEMENT flag EMPTY>
<!ATTLIST flag
   dx CDATA #REQUIRED
   dy CDATA #REQUIRED
>


<!ELEMENT stack EMPTY>
<!ATTLIST stack
   dx CDATA #REQUIRED
   dy CDATA #REQUIRED
   buildrequired CDATA #REQUIRED
   material %material; #REQUIRED
>

<!ELEMENT bricklayer EMPTY>
<!ATTLIST bricklayer
   dx CDATA #REQUIRED
   dy CDATA #REQUIRED
   direction %direction; #REQUIRED
>

<!ELEMENT occupyer EMPTY>
<!ATTLIST occupyer
   offsetX CDATA #REQUIRED
   offsetY CDATA #REQUIRED
   type (INFANTARY|BOWMAN) #REQUIRED
   
   soldierX CDATA #REQUIRED
   soldierY CDATA #REQUIRED
   looksRight (true|false) "true" 
>

<!ELEMENT startjob EMPTY>
<!ATTLIST startjob
   name IDREF #REQUIRED
>

<!ELEMENT job EMPTY>
<!ATTLIST job
   name ID #REQUIRED
   type %jobtype; #REQUIRED
   successjob IDREF #REQUIRED
   failjob IDREF #REQUIRED
   dx CDATA #IMPLIED
   dy CDATA #IMPLIED
   time CDATA #IMPLIED
   material %material; #IMPLIED
   direction %direction; #IMPLIED
   search %searchtype; #IMPLIED
>

<!ELEMENT image EMPTY>
<!ATTLIST image
   for (GUI|BUILD|FINAL) #REQUIRED
   type %imagelinktype; #REQUIRED
   file CDATA #REQUIRED
   sequence CDATA #REQUIRED
   image CDATA #REQUIRED
>

<!ELEMENT buildmark EMPTY>
<!ATTLIST buildmark
   dx CDATA #REQUIRED
   dy CDATA #REQUIRED
>

<!ELEMENT attacker EMPTY>
<!ATTLIST attacker
   dx CDATA #REQUIRED
   dy CDATA #REQUIRED
>

=== AdronTech/settlers-remake/assets/buildings/medium_livinghouse.xml
<?xml version="1.1" encoding="UTF-8"?><!DOCTYPE building SYSTEM "building.dtd">
<building worker="">
	<ground groundtype="GRASS"/>
	<ground groundtype="EARTH"/>
	<ground groundtype="FLATTENED"/>

	<blocked dx="4" dy="3" />
	<blocked dx="3" dy="2" />
	<blocked dx="3" dy="3" />
	<blocked dx="3" dy="4" />
	<blocked dx="2" dy="4" />
	<blocked dx="1" dy="3" />
	<blocked dx="1" dy="2" />
	<blocked dx="2" dy="3" />
	<blocked dx="2" dy="2" />
	<blocked dx="2" dy="1" />
	<blocked dx="1" dy="1" />
	<blocked dx="1" dy="0" />
	<blocked dx="2" dy="-1" />
	<blocked dx="3" dy="0" />
	<blocked dx="4" dy="2" />
	<blocked dx="5" dy="2" />
	<blocked dx="5" dy="3" />
	<blocked dx="5" dy="1" />
	<blocked dx="5" dy="0" />
	<blocked dx="4" dy="0" />
	<blocked dx="3" dy="-1" />
	<blocked dx="4" dy="-1" />
	<blocked dx="2" dy="-2" />
	<blocked dx="1" dy="-3" />
	<blocked dx="-1" dy="2" />
	<blocked dx="-1" dy="1" />
	<blocked dx="-1" dy="0" />
	<blocked dx="-1" dy="-1" />
	<blocked dx="-1" dy="-2" />
	<blocked dx="-1" dy="-3" />
	<blocked dx="-1" dy="-4" />
	<blocked dx="-2" dy="-3" />
	<blocked dx="-2" dy="-4" />
	<blocked dx="0" dy="-3" />
	<blocked dx="1" dy="-2" />
	<blocked dx="1" dy="-1" />
	<blocked dx="3" dy="-2" />
	<blocked dx="2" dy="-3" />
	<blocked dx="1" dy="-4" />
	<blocked dx="0" dy="-4" />
	<blocked dx="-1" dy="-5" />
	<blocked dx="-2" dy="-6" />
	<blocked dx="-2" dy="-5" />
	<blocked dx="0" dy="-2" />
	<blocked dx="0" dy="-1" />
	<blocked dx="0" dy="0" />
	<blocked dx="0" dy="1" />
	<door dx="0" dy="2" />
	<stack dx="6" dy="6" material="PLANK" buildrequired="5" />
	<stack dx="7" dy="4" material="STONE" buildrequired="8" />

	<bricklayer dx="-1" dy="3" direction="NORTH_EAST"/>
	<bricklayer dx="2" dy="5" direction="NORTH_EAST"/>
	<bricklayer dx="4" dy="4" direction="NORTH_WEST"/>
	<bricklayer dx="6" dy="4" direction="NORTH_WEST"/>
	<bricklayer dx="6" dy="2" direction="NORTH_WEST"/>

	<flag dx="-2" dy="3" />
	
	<image file="14" for="GUI" type="GUI" sequence="75" image="0"/>
	</building>

=== AdronTech/settlers-remake/resources/buildings/slaughterhouse.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE building SYSTEM "building.dtd" >
<building worker="SLAUGHTERER">
	<ground groundtype="GRASS" />
	<ground groundtype="EARTH" />
	<ground groundtype="FLATTENED" />
	
		<blocked dx="-3" dy="0" block="true" />
	<blocked dx="-3" dy="-1" block="true" />
	<blocked dx="-3" dy="-2" block="true" />
	<blocked dx="-3" dy="-3" block="true" />
	<blocked dx="-2" dy="-3" block="true" />
	<blocked dx="-1" dy="-3" block="true" />
	<blocked dx="0" dy="-2" block="true" />
	<blocked dx="1" dy="-1" block="true" />
	<blocked dx="-2" dy="-4" block="true" />
	<blocked dx="-3" dy="-4" block="true" />
	<blocked dx="-1" dy="-2" block="true" />
	<blocked dx="0" dy="-1" block="true" />
	<blocked dx="1" dy="0" block="true" />
	<blocked dx="0" dy="0" block="true" />
	<blocked dx="1" dy="1" block="true" />
	<blocked dx="-1" dy="-1" block="true" />
	<blocked dx="-2" dy="-2" block="true" />
	<blocked dx="-2" dy="-1" block="true" />
	<blocked dx="-1" dy="0" block="true" />
	<blocked dx="0" dy="1" block="true" />
	<blocked dx="1" dy="2" block="true" />
	<blocked dx="-2" dy="0" block="true" />
	<blocked dx="-1" dy="1" block="true" />
	<blocked dx="0" dy="2" block="true" />
	<blocked dx="1" dy="3" block="true" />
	<blocked dx="-2" dy="1" block="true" />
	<blocked dx="0" dy="3" block="true" />
	<blocked dx="2" dy="0" block="true" />
	<blocked dx="2" dy="1" block="true" />
	<blocked dx="2" dy="2" block="true" />
	<blocked dx="2" dy="3" block="true" />
	<blocked dx="2" dy="4" block="true" />
	<blocked dx="3" dy="3" block="true" />
	<blocked dx="3" dy="2" block="true" />
	<blocked dx="3" dy="1" block="true" />
	<blocked dx="4" dy="2" block="true" />
	<blocked dx="4" dy="1" block="true" />
	<blocked dx="5" dy="2" block="true" />
	<blocked dx="6" dy="3" block="true" />
	<blocked dx="6" dy="4" block="true" />
	<blocked dx="7" dy="5" block="true" />
	<blocked dx="7" dy="4" block="true" />
	<blocked dx="7" dy="6" block="true" />
	<blocked dx="5" dy="3" block="true" />
	<blocked dx="-2" dy="2" block="false" />
	<blocked dx="-1" dy="3" block="false" />
	<blocked dx="0" dy="4" block="false" />
	<blocked dx="1" dy="4" block="false" />
	<blocked dx="-3" dy="1" block="false" />
	<blocked dx="-4" dy="0" block="false" />
	<blocked dx="-4" dy="-1" block="false" />
	<blocked dx="-4" dy="-2" block="false" />
	<blocked dx="-4" dy="-3" block="false" />
	<blocked dx="-4" dy="-4" block="false" />
	<blocked dx="-4" dy="-5" block="false" />
	<blocked dx="-3" dy="-5" block="false" />
	<blocked dx="-2" dy="-5" block="false" />
	<blocked dx="-1" dy="-4" block="false" />
	<blocked dx="0" dy="-3" block="false" />
	<blocked dx="1" dy="-2" block="false" />
	<blocked dx="2" dy="-1" block="false" />
	<blocked dx="6" dy="6" block="false" />
	<blocked dx="6" dy="5" block="false" />
	<blocked dx="5" dy="4" block="false" />
	<blocked dx="4" dy="3" block="false" />
	<blocked dx="4" dy="4" block="false" />
	<blocked dx="5" dy="5" block="false" />
	<blocked dx="3" dy="4" block="false" />
	<blocked dx="2" dy="5" block="false" />
	<blocked dx="3" dy="5" block="false" />
	<blocked dx="4" dy="5" block="false" />
	<blocked dx="1" dy="5" block="false" />
	<blocked dx="-4" dy="1" block="false" />
	<blocked dx="-3" dy="2" block="false" />
	<blocked dx="-2" dy="3" block="false" />
	<blocked dx="-1" dy="4" block="false" />
	<blocked dx="3" dy="0" block="false" />
	<blocked dx="4" dy="0" block="false" />
	<blocked dx="5" dy="1" block="false" />
	<blocked dx="6" dy="2" block="false" />
	<blocked dx="7" dy="3" block="false" />
	<blocked dx="8" dy="5" block="false" />
	<blocked dx="8" dy="6" block="false" />
	<blocked dx="8" dy="7" block="false" />
	<blocked dx="7" dy="7" block="false" />
	<blocked dx="-1" dy="2" block="false" />
	<door dx="-1" dy="2" />
	<stack dx="2" dy="5" material="PLANK" buildrequired="1" />
	<stack dx="4" dy="5" material="STONE" buildrequired="1" />
	<stack dx="-3" dy="2" material="PIG" buildrequired="0" />
	<bricklayer dx="-3" dy="1" direction="NORTH_EAST" />
	<bricklayer dx="0" dy="4" direction="NORTH_EAST" />
	<bricklayer dx="3" dy="4" direction="NORTH_WEST" />
	<bricklayer dx="4" dy="3" direction="NORTH_WEST" />
	<flag dx="-4" dy="-5" />
	<buildmark dx="-3" dy="0" />
	<buildmark dx="0" dy="3" />
	<buildmark dx="3" dy="1" />
	<buildmark dx="3" dy="3" />
	<buildmark dx="-2" dy="-4" />
	<buildmark dx="7" dy="6" />
	<buildmark dx="5" dy="2" />
	
	<image file="14" for="GUI" type="GUI" sequence="39" image="0"/>
	<image file="13" for="FINAL" type="SETTLER" sequence="23" image="0"/>
	<image file="13" for="BUILD" type="SETTLER" sequence="23" image="1"/>

	<!-- drop stack for meat: 1, 4 -->

</building>

=== AdronTech/settlers-remake/resources/buildings/charcoal_burner.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE building SYSTEM "building.dtd">
<building worker="CHARCOAL_BURNER">
	<ground groundtype="GRASS"/>
	<ground groundtype="EARTH"/>
	<ground groundtype="FLATTENED"/>
	<blocked dx="-1" dy="2" block="true" />
	<blocked dx="-2" dy="1" block="true" />
	<blocked dx="0" dy="2" block="true" />
	<blocked dx="0" dy="1" block="true" />
	<blocked dx="-1" dy="1" block="true" />
	<blocked dx="-2" dy="0" block="true" />
	<blocked dx="-2" dy="-1" block="true" />
	<blocked dx="-1" dy="0" block="true" />
	<blocked dx="-1" dy="-1" block="true" />
	<blocked dx="0" dy="0" block="true" />
	<blocked dx="1" dy="-1" block="true" />
	<blocked dx="2" dy="0" block="true" />
	<blocked dx="1" dy="0" block="true" />
	<blocked dx="3" dy="2" block="true" />
	<blocked dx="4" dy="3" block="true" />
	<blocked dx="5" dy="3" block="true" />
	<blocked dx="5" dy="1" block="true" />
	<blocked dx="4" dy="2" block="true" />
	<blocked dx="5" dy="2" block="true" />
	<blocked dx="4" dy="0" block="true" />
	<blocked dx="4" dy="1" block="true" />
	<blocked dx="3" dy="1" block="true" />
	<blocked dx="2" dy="1" block="true" />
	<blocked dx="1" dy="1" block="true" />
	<blocked dx="3" dy="0" block="true" />
	<blocked dx="2" dy="-1" block="true" />
	<blocked dx="3" dy="-1" block="true" />
	<blocked dx="-2" dy="-2" block="true" />
	<blocked dx="0" dy="-2" block="true" />
	<blocked dx="1" dy="-2" block="true" />
	<blocked dx="2" dy="-2" block="true" />
	<blocked dx="3" dy="3" block="true" />
	<blocked dx="0" dy="-1" block="false" />
	<blocked dx="1" dy="2" block="false" />
	<blocked dx="2" dy="3" block="false" />
	<blocked dx="3" dy="4" block="false" />
	<blocked dx="4" dy="4" block="false" />
	<blocked dx="5" dy="4" block="false" />
	<blocked dx="6" dy="4" block="false" />
	<blocked dx="6" dy="3" block="false" />
	<blocked dx="6" dy="2" block="false" />
	<blocked dx="5" dy="0" block="false" />
	<blocked dx="4" dy="-1" block="false" />
	<blocked dx="3" dy="-2" block="false" />
	<blocked dx="2" dy="-3" block="false" />
	<blocked dx="1" dy="-3" block="false" />
	<blocked dx="0" dy="-3" block="false" />
	<blocked dx="-1" dy="-3" block="false" />
	<blocked dx="-1" dy="-2" block="false" />
	<blocked dx="-2" dy="-3" block="false" />
	<blocked dx="-3" dy="-3" block="false" />
	<blocked dx="-3" dy="-2" block="false" />
	<blocked dx="-3" dy="-1" block="false" />
	<blocked dx="-3" dy="0" block="false" />
	<blocked dx="-2" dy="2" block="false" />
	<blocked dx="-1" dy="3" block="false" />
	<blocked dx="0" dy="3" block="false" />
	<blocked dx="1" dy="3" block="false" />
	<blocked dx="2" dy="4" block="false" />
	<blocked dx="1" dy="4" block="false" />
	<blocked dx="0" dy="4" block="false" />
	<blocked dx="2" dy="2" block="false" />
	<door dx="2" dy="2" />
	<stack dx="0" dy="4" material="STONE" buildrequired="3" />
	<stack dx="3" dy="4" material="PLANK" buildrequired="4" />
	<stack dx="1" dy="4" material="PLANK" buildrequired="0" />
	<bricklayer dx="2" dy="3" direction="NORTH_EAST" />
	<bricklayer dx="6" dy="4" direction="NORTH_WEST" />
	<bricklayer dx="6" dy="2" direction="NORTH_WEST" />
	<bricklayer dx="1" dy="2" direction="NORTH_WEST" />
	<bricklayer dx="-1" dy="3" direction="NORTH_EAST" />
	<flag dx="0" dy="-1" />
	<buildmark dx="3" dy="3" />
	<buildmark dx="5" dy="3" />
	<buildmark dx="4" dy="0" />
	<buildmark dx="2" dy="-2" />
	<buildmark dx="0" dy="-2" />
	<buildmark dx="-2" dy="-2" />
	<buildmark dx="-2" dy="1" />
	<buildmark dx="0" dy="2" />
	<buildmark dx="1" dy="1" />

	<image file="14" for="GUI" type="GUI" sequence="81" image="0"/>

	<startjob name="gohome" />

	<!-- go home -->
	<job name="gohome" type="GO_TO" successjob="hide" failjob="gohome_wait"
		dx="2" dy="2" />
	<!-- go home failed, retry -->
	<job name="gohome_wait" type="WAIT" successjob="gohome" failjob="gohome_wait"
		time="1.0" />

	<!-- arrive at front door => hide -->
	<job name="hide" type="HIDE" successjob="reset" failjob="gohome_wait" />
	<job name="reset" type="SET_MATERIAL" successjob="wait_at_home"
		failjob="wait_at_home" material="NO_MATERIAL" />
	<job name="wait_at_home" type="WAIT" successjob="checkplank" failjob="wait_at_home"
		time="1" />

	<job name="checkplank" type="AVAILABLE" successjob="checkcoal"
		failjob="wait_at_home" dx="1" dy="4" material="PLANK" />
	<job name="checkcoal" type="NOT_FULL" successjob="show"
		failjob="wait_at_home" dx="4" dy="4" material="COAL" />

	<job name="show" type="SHOW" successjob="walkA1" failjob="gohome" dx="2" dy="2"/>
	<job name="walkA1" type="WALK" successjob="walkA2" failjob="walkA2" direction="SOUTH_WEST"/>
	<job name="walkA2" type="WALK" successjob="walkA3" failjob="walkA3" direction="SOUTH_WEST" />

	<job name="walkA3" type="WALK" successjob="take1" failjob="gohome" direction="WEST" />
	
	<job name="take1" type="DROP" successjob="take2" failjob="gohome" material="NO_MATERIAL" />
	<job name="take2" type="SET_MATERIAL" successjob="take3" failjob="gohome" material="PLANK" />
	<job name="take3" type="TAKE" successjob="walkB1" failjob="gohome" material="PLANK" />
	
	<job name="walkB1" type="WALK" successjob="walkB2" failjob="gohome" direction="NORTH_EAST" />
	<job name="walkB2" type="WALK" successjob="walkB3" failjob="gohome" direction="NORTH_EAST" />
	<job name="walkB3" type="LOOK_AT" successjob="work1" failjob="gohome" direction="NORTH_WEST" />
	<job name="work1" type="DROP" successjob="work2" failjob="gohome" material="NO_MATERIAL"/>
	<job name="work2" type="SET_MATERIAL" successjob="work3" failjob="gohome" material="NO_MATERIAL"/>
	<job name="work3" type="TAKE" successjob="work4" failjob="gohome" material="NO_MATERIAL"/>
	<job name="work4" type="WAIT" successjob="work5" failjob="gohome" time="2"/>
	<job name="work5" type="DROP" successjob="work6" failjob="gohome" material="NO_MATERIAL"/>
	<job name="work6" type="SET_MATERIAL" successjob="work7" failjob="gohome" material="COAL"/>
	<job name="work7" type="TAKE" successjob="walkC1" failjob="gohome" material="NO_MATERIAL"/>
	
	<job name="walkC1" type="WALK" successjob="walkC2" failjob="gohome" direction="SOUTH_EAST" />
	<job name="walkC2" type="WALK" successjob="drop1" failjob="gohome" direction="SOUTH_EAST" />
	
	<job name="drop1" type="DROP" successjob="drop2" failjob="gohome" material="COAL" />
	<job name="drop2" type="SET_MATERIAL" successjob="drop3" failjob="gohome" material="NO_MATERIAL" />
	<job name="drop3" type="TAKE" successjob="walkD1" failjob="gohome" material="NO_MATERIAL" />
	
	<job name="walkD1" type="WALK" successjob="walkD2" failjob="gohome" direction="NORTH_WEST" />
	<job name="walkD2" type="WALK" successjob="hide" failjob="gohome" direction="NORTH_EAST" />
</building>

=== AdronTech/settlers-remake/src/jsettlers/common/buildings/data/ironmine.xml
<?xml version="1.1" encoding="UTF-8"?><!DOCTYPE building SYSTEM "building.dtd">
<building worker="MINER" workradius="0"> 

	<blocked dx="1" dy="3" />
	<blocked dx="2" dy="3" />
	<blocked dx="1" dy="2" />
	<blocked dx="1" dy="1" />
	<blocked dx="0" dy="0" />
	<blocked dx="-1" dy="-1" />
	<blocked dx="-1" dy="0" />
	<blocked dx="-1" dy="1" />
	<blocked dx="0" dy="1" />
	<blocked dx="-2" dy="0" />
	<blocked dx="-2" dy="1" />
	<blocked dx="-2" dy="-1" />
	<blocked dx="-2" dy="-2" />
	<blocked dx="2" dy="2" />
	<blocked dx="2" dy="1" />
	<blocked dx="3" dy="1" />
	<blocked dx="2" dy="0" />
	<blocked dx="1" dy="-1" />
	<blocked dx="1" dy="0" />
	<blocked dx="0" dy="-1" />
	<blocked dx="-1" dy="-2" />
	
	<door dx="0" dy="2" />
	
	<stack dx="0" dy="3" material="PLANK" buildrequired="5" />
	<stack dx="3" dy="5" material="STONE" buildrequired="2" />
	
	<bricklayer dx="-1" dy="2" direction="NORTH_EAST" />
	<bricklayer dx="1" dy="4" direction="NORTH_EAST" />
	<bricklayer dx="3" dy="4" direction="NORTH_WEST" />
	<bricklayer dx="4" dy="3" direction="NORTH_WEST" />
	<bricklayer dx="4" dy="2" direction="NORTH_WEST" />
	
	<flag dx="-2" dy="-3" />

<!-- going home job -->
<!-- Es fehlt eine Zufallsregel, die die Lebensmittel und den noch vorhandenen Erz zusammen bringt. Für andere Minen kopieren und umändern. -->
	<startjob name="gohome" />
	<job name="gohome" 		type="GO_TO" 			successjob="hide" 			failjob="waithome" 	dx="0" dy="2"/>
	<job name="waithome" 	type="WAIT" 			successjob="gohome" 		failjob="waithome" 	time="10"/>
	<job name="hide" 		type="HIDE" 			successjob="wait"			failjob="gohome"	/>
	<job name="wait"		type="WAIT"				successjob="check"			failjob="gohome"	time="10" />
	<job name="check"		type="NOT_FULL"			successjob="getironore"		failjob="noironore"	dx="0" dy="4" />
	
	<job name="getironore"	type="SET_MATERIAL"		successjob="show_full"		failjob="gohome"	material="IRONORE" />
	<job name="show_full"	type="SHOW"				successjob="getironore1"	failjob="gohome"	dx="0" dy="2" />
	<job name="getironore1"	type="GO_TO"			successjob="getironore2"	failjob="gohome"	dx="0" dy="4" />
	<job name="getironore2"	type="LOOK_AT"			successjob="getironore3"	failjob="gohome"	direction="SOUTH_WEST" />
	<job name="getironore3"	type="DROP"				successjob="getironore4"	failjob="gohome"	material="IRONORE" />
	<job name="getironore4"	type="SET_MATERIAL"		successjob="gohome"			failjob="gohome"	material="NO_MATERIAL" />
	
	<job name="noironore"	type="SET_MATERIAL"		successjob="show_leer"		failjob="gohome"	material="BASKET" />
	<job name="show_leer"	type="SHOW"				successjob="noironore1"		failjob="gohome"	dx="0" dy="2" />
	<job name="noironore1"	type="GO_TO"			successjob="noironore2"		failjob="hide"		dx="0" dy="4" />
	<job name="noironore2"	type="LOOK_AT"			successjob="noironore3"		failjob="hide"		direction="SOUTH_WEST" />
	<job name="noironore3"	type="PLAY_ACTION1"		successjob="noironore4"		failjob="hide"		time="5.0" />
	<job name="noironore4"	type="SET_MATERIAL"		successjob="gohome"			failjob="gohome"	material="BASKET" />



</building>

=== AdronTech/settlers-remake/resources/buildings/castle.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE building SYSTEM "building.dtd" >
<building worker="" viewdistance="40">
	<ground groundtype="GRASS"/>
	<ground groundtype="EARTH"/>
	<ground groundtype="FLATTENED"/>

	<blocked dx="-5" dy="0" block="true" />
	<blocked dx="-4" dy="1" block="true" />
	<blocked dx="-3" dy="2" block="true" />
	<blocked dx="-2" dy="2" block="true" />
	<blocked dx="0" dy="4" block="true" />
	<blocked dx="-1" dy="2" block="true" />
	<blocked dx="-2" dy="1" block="true" />
	<blocked dx="-3" dy="1" block="true" />
	<blocked dx="-3" dy="0" block="true" />
	<blocked dx="-4" dy="0" block="true" />
	<blocked dx="-4" dy="-1" block="true" />
	<blocked dx="-5" dy="-1" block="true" />
	<blocked dx="-5" dy="-2" block="true" />
	<blocked dx="-5" dy="-3" block="true" />
	<blocked dx="-4" dy="-3" block="true" />
	<blocked dx="-4" dy="-4" block="true" />
	<blocked dx="-4" dy="-5" block="true" />
	<blocked dx="-3" dy="-5" block="true" />
	<blocked dx="-3" dy="-6" block="true" />
	<blocked dx="-3" dy="-7" block="true" />
	<blocked dx="-4" dy="-7" block="true" />
	<blocked dx="-4" dy="-6" block="true" />
	<blocked dx="-2" dy="-6" block="true" />
	<blocked dx="-1" dy="-5" block="true" />
	<blocked dx="0" dy="-4" block="true" />
	<blocked dx="1" dy="-3" block="true" />
	<blocked dx="2" dy="-2" block="true" />
	<blocked dx="3" dy="-1" block="true" />
	<blocked dx="4" dy="1" block="true" />
	<blocked dx="4" dy="0" block="true" />
	<blocked dx="3" dy="1" block="true" />
	<blocked dx="4" dy="2" block="true" />
	<blocked dx="4" dy="3" block="true" />
	<blocked dx="3" dy="0" block="true" />
	<blocked dx="3" dy="2" block="true" />
	<blocked dx="3" dy="3" block="true" />
	<blocked dx="3" dy="4" block="true" />
	<blocked dx="3" dy="5" block="true" />
	<blocked dx="3" dy="6" block="true" />
	<blocked dx="2" dy="5" block="true" />
	<blocked dx="1" dy="5" block="true" />
	<blocked dx="2" dy="6" block="true" />
	<blocked dx="1" dy="4" block="true" />
	<blocked dx="0" dy="3" block="true" />
	<blocked dx="-4" dy="-2" block="true" />
	<blocked dx="-3" dy="-4" block="true" />
	<blocked dx="-3" dy="-3" block="true" />
	<blocked dx="-3" dy="-2" block="true" />
	<blocked dx="-3" dy="-1" block="true" />
	<blocked dx="-2" dy="0" block="true" />
	<blocked dx="-2" dy="-1" block="true" />
	<blocked dx="-2" dy="-2" block="true" />
	<blocked dx="-2" dy="-3" block="true" />
	<blocked dx="-2" dy="-4" block="true" />
	<blocked dx="-2" dy="-5" block="true" />
	<blocked dx="-1" dy="-4" block="true" />
	<blocked dx="-1" dy="-3" block="true" />
	<blocked dx="-1" dy="-2" block="true" />
	<blocked dx="-1" dy="-1" block="true" />
	<blocked dx="-1" dy="0" block="true" />
	<blocked dx="-1" dy="1" block="true" />
	<blocked dx="0" dy="-3" block="true" />
	<blocked dx="0" dy="-2" block="true" />
	<blocked dx="0" dy="-1" block="true" />
	<blocked dx="0" dy="0" block="true" />
	<blocked dx="0" dy="1" block="true" />
	<blocked dx="0" dy="2" block="true" />
	<blocked dx="1" dy="3" block="true" />
	<blocked dx="1" dy="2" block="true" />
	<blocked dx="1" dy="1" block="true" />
	<blocked dx="1" dy="0" block="true" />
	<blocked dx="1" dy="-1" block="true" />
	<blocked dx="1" dy="-2" block="true" />
	<blocked dx="2" dy="-1" block="true" />
	<blocked dx="2" dy="0" block="true" />
	<blocked dx="2" dy="1" block="true" />
	<blocked dx="2" dy="2" block="true" />
	<blocked dx="2" dy="3" block="true" />
	<blocked dx="2" dy="4" block="true" />
	<blocked dx="4" dy="7" block="false" />
	<blocked dx="4" dy="6" block="false" />
	<blocked dx="4" dy="5" block="false" />
	<blocked dx="4" dy="4" block="false" />
	<blocked dx="5" dy="4" block="false" />
	<blocked dx="5" dy="3" block="false" />
	<blocked dx="5" dy="2" block="false" />
	<blocked dx="5" dy="1" block="false" />
	<blocked dx="5" dy="0" block="false" />
	<blocked dx="4" dy="-1" block="false" />
	<blocked dx="3" dy="-2" block="false" />
	<blocked dx="2" dy="-3" block="false" />
	<blocked dx="1" dy="-4" block="false" />
	<blocked dx="0" dy="-5" block="false" />
	<blocked dx="-1" dy="-6" block="false" />
	<blocked dx="-2" dy="-7" block="false" />
	<blocked dx="-3" dy="-8" block="false" />
	<blocked dx="-4" dy="-8" block="false" />
	<blocked dx="-5" dy="-8" block="false" />
	<blocked dx="-5" dy="-6" block="false" />
	<blocked dx="-5" dy="-7" block="false" />
	<blocked dx="-5" dy="-5" block="false" />
	<blocked dx="-5" dy="-4" block="false" />
	<blocked dx="-6" dy="-4" block="false" />
	<blocked dx="-6" dy="-2" block="false" />
	<blocked dx="-6" dy="-3" block="false" />
	<blocked dx="-6" dy="-1" block="false" />
	<blocked dx="-6" dy="0" block="false" />
	<blocked dx="-5" dy="1" block="false" />
	<blocked dx="-4" dy="2" block="false" />
	<blocked dx="-3" dy="3" block="false" />
	<blocked dx="-2" dy="3" block="false" />
	<blocked dx="-1" dy="4" block="false" />
	<blocked dx="0" dy="5" block="false" />
	<blocked dx="1" dy="6" block="false" />
	<blocked dx="3" dy="8" block="false" />
	<blocked dx="3" dy="7" block="false" />
	<blocked dx="4" dy="8" block="false" />
	<blocked dx="-2" dy="4" block="false" />
	<blocked dx="-1" dy="5" block="false" />
	<blocked dx="0" dy="6" block="false" />
	<blocked dx="-6" dy="1" block="false" />
	<blocked dx="-5" dy="2" block="false" />
	<blocked dx="-4" dy="3" block="false" />
	<blocked dx="-3" dy="4" block="false" />
	<blocked dx="2" dy="7" block="false" />
	<blocked dx="2" dy="8" block="false" />
	<blocked dx="3" dy="9" block="false" />
	<blocked dx="1" dy="7" block="false" />
	<blocked dx="4" dy="9" block="false" />
	<blocked dx="5" dy="9" block="false" />
	<blocked dx="5" dy="8" block="false" />
	<blocked dx="5" dy="7" block="false" />
	<blocked dx="5" dy="6" block="false" />
	<blocked dx="5" dy="5" block="false" />
	<blocked dx="-1" dy="3" block="false" />
	<door dx="-1" dy="3" />
	<stack dx="1" dy="7" material="STONE" buildrequired="7" />
	<stack dx="4" dy="8" material="PLANK" buildrequired="5" />
	<bricklayer dx="-4" dy="2" direction="NORTH_EAST" />
	<bricklayer dx="-2" dy="3" direction="NORTH_EAST" />
	<bricklayer dx="1" dy="6" direction="NORTH_EAST" />
	<bricklayer dx="4" dy="7" direction="NORTH_WEST" />
	<bricklayer dx="4" dy="4" direction="NORTH_WEST" />
	<bricklayer dx="5" dy="3" direction="NORTH_WEST" />
	<flag dx="-1" dy="5" />
	<buildmark dx="-5" dy="0" />
	<buildmark dx="-3" dy="2" />
	<buildmark dx="1" dy="5" />
	<buildmark dx="3" dy="7" />
	<buildmark dx="4" dy="0" />
	<buildmark dx="-3" dy="-7" />
	
	<image file="14" for="GUI" type="GUI" sequence="63" image="0"/>
    <image file="13" type="SETTLER" for="FINAL" image="0" sequence="16"/>
    <image file="13" type="SETTLER" for="BUILD" image="1" sequence="16"/>
    <image file="13" type="SETTLER" for="FINAL" image="2" sequence="16"/>
	
</building>
