=== AdronTech/settlers-remake/resources/buildings/building.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ENTITY % imagelinktype "(SETTLER| GUI| LANDSCAPE)">

<!ENTITY % material "(NO_MATERIAL|
	AXE|
	BOW|
	BLADE|
	BREAD|
	COAL|
	CROP|
	FISH|
	FISHINGROD|
	FLOUR|
	GOLD|
	GOLDORE|
	HAMMER|
	IRON|
	IRONORE|
	MEAT|
	PICK|
	PIG|
	PLANK|
	SAW|
	SCYTHE|
	SPEAR|
	STONE|
	SWORD|
	TRUNK|
	WATER|
	WINE|
	WHITE_BREAD|
	BASKET|
	TREE|
	PLANT)">
<!ENTITY % jobtype "(
	WAIT|
	WALK|
	SHOW|
	HIDE|
	SET_MATERIAL|
	TAKE|
	DROP|
	PRE_SEARCH|
	PRE_SEARCH_IN_AREA|
	FOLLOW_SEARCHED|
	GO_TO|
	LOOK_AT|
	PLAY_ACTION1|
	PLAY_ACTION2|
	EXECUTE|
	AVAILABLE|
	NOT_FULL|
	LOOK_AT_SEARCHED|
	IS_PRODUCTIVE|
	SMOKE_ON|
	SMOKE_OFF|
	START_WORKING|
	STOP_WORKING|
	REMOTETAKE|
	PIG_PLACE|
	PIG_REMOVE|
	PIG_IS_ADULT|
	PIG_IS_THERE|
	POP_TOOL|
	POP_WEAPON|
	DROP_POPPED)
">
<!ENTITY % direction "(EAST| SOUTH_EAST| SOUTH_WEST| WEST | NORTH_WEST | NORTH_EAST)
">

<!ENTITY % searchtype "(FOREIGN_GROUND|
	CUTTABLE_TREE|
	CUTTABLE_STONE|
	PLANTABLE_TREE|
	PLANTABLE_CORN|
	CUTTABLE_CORN|
	FISHABLE|
	RIVER|
	ENEMY)
">
<!ENTITY % groundtype "(
	GRASS|
	DRY_GRASS|
	DESERT|
	EARTH|
	MOUNTAIN|
	SNOW|
	WATER|
	SAND|
	FLATTENED|
	RIVER1|
	RIVER2|
	RIVER3|
	RIVER4|
	MOUNTAINBORDER
)">
<!ELEMENT building (ground+, blocked+, door, stack*, bricklayer+, flag, buildmark*, workcenter?, image*, occupyer*, startjob?, job*, attacker*) >

<!ATTLIST building
   worker CDATA #REQUIRED
   workradius CDATA #IMPLIED
   viewdistance CDATA #IMPLIED
>

<!ELEMENT ground EMPTY>
<!ATTLIST ground
	groundtype %groundtype; #REQUIRED
>

<!ELEMENT workcenter EMPTY>
<!ATTLIST workcenter
   dx CDATA #REQUIRED
   dy CDATA #REQUIRED
>

<!ELEMENT blocked EMPTY>
<!ATTLIST blocked
   dx CDATA #REQUIRED
   dy CDATA #REQUIRED
   block (true|false) "true"
>

<!ELEMENT door EMPTY>
<!ATTLIST door
   dx CDATA #REQUIRED
   dy CDATA #REQUIRED
>

<!ELEMENT flag EMPTY>
<!ATTLIST flag
   dx CDATA #REQUIRED
   dy CDATA #REQUIRED
>


<!ELEMENT stack EMPTY>
<!ATTLIST stack
   dx CDATA #REQUIRED
   dy CDATA #REQUIRED
   buildrequired CDATA #REQUIRED
   material %material; #REQUIRED
>

<!ELEMENT bricklayer EMPTY>
<!ATTLIST bricklayer
   dx CDATA #REQUIRED
   dy CDATA #REQUIRED
   direction %direction; #REQUIRED
>

<!ELEMENT occupyer EMPTY>
<!ATTLIST occupyer
   offsetX CDATA #REQUIRED
   offsetY CDATA #REQUIRED
   type (INFANTARY|BOWMAN) #REQUIRED
   
   soldierX CDATA #REQUIRED
   soldierY CDATA #REQUIRED
   looksRight (true|false) "true" 
>

<!ELEMENT startjob EMPTY>
<!ATTLIST startjob
   name IDREF #REQUIRED
>

<!ELEMENT job EMPTY>
<!ATTLIST job
   name ID #REQUIRED
   type %jobtype; #REQUIRED
   successjob IDREF #REQUIRED
   failjob IDREF #REQUIRED
   dx CDATA #IMPLIED
   dy CDATA #IMPLIED
   time CDATA #IMPLIED
   material %material; #IMPLIED
   direction %direction; #IMPLIED
   search %searchtype; #IMPLIED
>

<!ELEMENT image EMPTY>
<!ATTLIST image
   for (GUI|BUILD|FINAL) #REQUIRED
   type %imagelinktype; #REQUIRED
   file CDATA #REQUIRED
   sequence CDATA #REQUIRED
   image CDATA #REQUIRED
>

<!ELEMENT buildmark EMPTY>
<!ATTLIST buildmark
   dx CDATA #REQUIRED
   dy CDATA #REQUIRED
>

<!ELEMENT attacker EMPTY>
<!ATTLIST attacker
   dx CDATA #REQUIRED
   dy CDATA #REQUIRED
>

=== AdronTech/settlers-remake/resources/buildings/ironmine.xml
<?xml version="1.1" encoding="UTF-8"?><!DOCTYPE building SYSTEM "building.dtd">
<building worker="MINER" workradius="0">
    <ground groundtype="MOUNTAIN" />
    <blocked dx="1" dy="3" block="true" />
    <blocked dx="2" dy="3" block="true" />
    <blocked dx="1" dy="2" block="true" />
    <blocked dx="1" dy="1" block="true" />
    <blocked dx="0" dy="0" block="true" />
    <blocked dx="-1" dy="-1" block="true" />
    <blocked dx="-1" dy="0" block="true" />
    <blocked dx="-1" dy="1" block="true" />
    <blocked dx="0" dy="1" block="true" />
    <blocked dx="-2" dy="0" block="true" />
    <blocked dx="-2" dy="-1" block="true" />
    <blocked dx="-2" dy="-2" block="true" />
    <blocked dx="2" dy="2" block="true" />
    <blocked dx="2" dy="1" block="true" />
    <blocked dx="3" dy="1" block="true" />
    <blocked dx="2" dy="0" block="true" />
    <blocked dx="1" dy="-1" block="true" />
    <blocked dx="1" dy="0" block="true" />
    <blocked dx="0" dy="-1" block="true" />
    <blocked dx="-1" dy="-2" block="true" />
    <blocked dx="-2" dy="-3" block="true" />
    <blocked dx="-1" dy="-3" block="true" />
    <blocked dx="4" dy="2" block="false" />
    <blocked dx="4" dy="3" block="false" />
    <blocked dx="3" dy="2" block="false" />
    <blocked dx="3" dy="3" block="false" />
    <blocked dx="4" dy="4" block="false" />
    <blocked dx="3" dy="4" block="false" />
    <blocked dx="3" dy="5" block="false" />
    <blocked dx="2" dy="4" block="false" />
    <blocked dx="2" dy="5" block="false" />
    <blocked dx="1" dy="4" block="false" />
    <blocked dx="0" dy="3" block="false" />
    <blocked dx="0" dy="2" block="false" />
    <blocked dx="-1" dy="2" block="false" />
    <blocked dx="-2" dy="1" block="false" />
    <blocked dx="-3" dy="0" block="false" />
    <blocked dx="-3" dy="-1" block="false" />
    <blocked dx="-3" dy="-2" block="false" />
    <blocked dx="-3" dy="-3" block="false" />
    <blocked dx="-3" dy="-4" block="false" />
    <blocked dx="-2" dy="-4" block="false" />
    <blocked dx="-1" dy="-4" block="false" />
    <blocked dx="0" dy="-3" block="false" />
    <blocked dx="1" dy="-2" block="false" />
    <blocked dx="2" dy="-1" block="false" />
    <blocked dx="3" dy="0" block="false" />
    <blocked dx="4" dy="1" block="false" />
    <door dx="0" dy="2" />
    <!-- materials checked with original -->
    <stack dx="0" dy="3" material="PLANK" buildrequired="4" />
    <stack dx="3" dy="5" material="STONE" buildrequired="1" />
    <stack dx="3" dy="4" material="BREAD" buildrequired="0" />
    <stack dx="3" dy="2" material="MEAT" buildrequired="0" />
    <stack dx="4" dy="2" material="FISH" buildrequired="0" />
    <bricklayer dx="-1" dy="2" direction="NORTH_EAST" />
    <bricklayer dx="1" dy="4" direction="NORTH_EAST" />
    <bricklayer dx="3" dy="4" direction="NORTH_WEST" />
    <bricklayer dx="4" dy="3" direction="NORTH_WEST" />
    <bricklayer dx="4" dy="2" direction="NORTH_WEST" />
    <flag dx="0" dy="0" />
    <buildmark dx="-2" dy="0" />
    <buildmark dx="-2" dy="-3" />
    <buildmark dx="1" dy="3" />
    <buildmark dx="1" dy="0" />
    <buildmark dx="3" dy="1" />

    <image file="14" for="GUI" type="GUI" sequence="45" image="0" />
    <image file="13" for="FINAL" type="SETTLER" sequence="4" image="0" />
    <image file="13" for="BUILD" type="SETTLER" sequence="4" image="1" />

    <!-- going home job -->
    <startjob name="gohome" />
    <job name="gohome" type="GO_TO" successjob="hide" failjob="hide" dx="0" dy="2" />


    <job name="hide" type="HIDE" successjob="A_wait" failjob="A_wait" />

    <!-- Wait for MEAT -->
    <job name="A_wait" type="WAIT" successjob="A_checkore" failjob="A_checkore" time="10" />
    <job name="A_checkore" type="NOT_FULL" successjob="A_checkfood" failjob="B_wait" dx="0" dy="4" material="IRONORE" />
    <job name="A_checkfood" type="AVAILABLE" successjob="mine_meat" failjob="B_wait" material="MEAT" dx="3" dy="2" />

    <!-- Wait some more for MEAT -->
    <job name="B_wait" type="WAIT" successjob="B_checkore" failjob="B_checkore" time="10" />
    <job name="B_checkore" type="NOT_FULL" successjob="B_checkfood" failjob="C_wait" dx="0" dy="4" material="IRONORE" />
    <job name="B_checkfood" type="AVAILABLE" successjob="mine_meat" failjob="C_wait" material="MEAT" dx="3" dy="2" />

    <!-- Wait for BREAD -->
    <job name="C_wait" type="WAIT" successjob="C_checkore" failjob="C_checkore" time="10" />
    <job name="C_checkore" type="NOT_FULL" successjob="C_checkfood1" failjob="D_wait" dx="0" dy="4" material="IRONORE" />
    <job name="C_checkfood1" type="AVAILABLE" successjob="mine_meat" failjob="C_checkfood2" material="MEAT" dx="3" dy="2" />
    <job name="C_checkfood2" type="AVAILABLE" successjob="mine_bread" failjob="D_wait" material="BREAD" dx="3" dy="4" />

    <!-- Wait for FISH -->
    <job name="D_wait" type="WAIT" successjob="D_checkore" failjob="D_checkore" time="10" />
    <job name="D_checkore" type="NOT_FULL" successjob="D_checkfood1" failjob="E_wait" dx="0" dy="4" material="IRONORE" />
    <job name="D_checkfood1" type="AVAILABLE" successjob="mine_meat" failjob="D_checkfood2" material="MEAT" dx="3" dy="2" />
    <job name="D_checkfood2" type="AVAILABLE" successjob="mine_bread" failjob="D_checkfood3" material="BREAD" dx="3" dy="4" />
    <job name="D_checkfood3" type="AVAILABLE" successjob="mine_fish" failjob="E_wait" material="FISH" dx="4" dy="2" />

    <!-- Wait for FISH -->
    <job name="E_wait" type="WAIT" successjob="E_checkore" failjob="E_checkore" time="10" />
    <job name="E_checkore" type="NOT_FULL" successjob="E_checkfood1" failjob="E_wait" dx="0" dy="4" material="IRONORE" />
    <job name="E_checkfood1" type="AVAILABLE" successjob="mine_meat" failjob="E_checkfood2" material="MEAT" dx="3" dy="2" />
    <job name="E_checkfood2" type="AVAILABLE" successjob="mine_bread" failjob="E_checkfood3" material="BREAD" dx="3" dy="4" />
    <job name="E_checkfood3" type="AVAILABLE" successjob="mine_fish" failjob="E_wait" material="FISH" dx="4" dy="2" />

    <job name="mine_meat" type="REMOTETAKE" successjob="mine" failjob="E_wait" material="MEAT" dx="3" dy="2" />
    <job name="mine_bread" type="REMOTETAKE" successjob="mine" failjob="E_wait" material="BREAD" dx="3" dy="4" />
    <job name="mine_fish" type="REMOTETAKE" successjob="mine" failjob="E_wait" material="FISH" dx="4" dy="2" />

    <job name="mine" type="IS_PRODUCTIVE" successjob="successful" failjob="noironore1" />

    <!-- successful mining -->
    <job name="successful" type="NOT_FULL" successjob="successfuls" failjob="successfuls" dx="0" dy="4" material="IRONORE" />
    <job name="successfuls" type="SET_MATERIAL" successjob="show_full" failjob="gohome" material="IRONORE" />
    <job name="show_full" type="SHOW" successjob="successful1" failjob="gohome" dx="0" dy="2" />
    <job name="successful1" type="WALK" successjob="successful2" failjob="gohome" direction="SOUTH_WEST" />
    <job name="successful2" type="WALK" successjob="successful3" failjob="gohome" direction="SOUTH_WEST" />
    <job name="successful3" type="LOOK_AT" successjob="successful4" failjob="gohome" direction="SOUTH_WEST" />
    <job name="successful4" type="DROP" successjob="successful5" failjob="gohome" material="IRONORE" />
    <job name="successful5" type="SET_MATERIAL" successjob="successful6" failjob="gohome" material="NO_MATERIAL" />
    <job name="successful6" type="TAKE" successjob="successful7" failjob="gohome" material="NO_MATERIAL" />
    <job name="successful7" type="WALK" successjob="successful8" failjob="gohome" direction="NORTH_EAST" />
    <job name="successful8" type="WALK" successjob="hide" failjob="hide" direction="NORTH_EAST" />

    <!-- failed mining -->
    <job name="noironore1" type="SET_MATERIAL" successjob="noironore2" failjob="gohome" material="BASKET" />
    <job name="noironore2" type="SHOW" successjob="noironore4" failjob="gohome" dx="0" dy="2" />
    <job name="noironore4" type="WALK" successjob="noironore5" failjob="gohome" direction="SOUTH_WEST" />
    <job name="noironore5" type="LOOK_AT" successjob="noironore6" failjob="gohome" direction="SOUTH_WEST" />
    <job name="noironore6" type="PLAY_ACTION1" successjob="noironore7" failjob="gohome" time="5.0" />
    <job name="noironore7" type="WALK" successjob="hide" failjob="hide" direction="NORTH_EAST" />
</building>

=== AdronTech/settlers-remake/resources/buildings/mill.xml
<?xml version="1.1" encoding="UTF-8"?><!DOCTYPE building SYSTEM "building.dtd">

<building worker="MILLER" workradius="10">
	<ground groundtype="GRASS" />
	<ground groundtype="EARTH" />
	<ground groundtype="FLATTENED" />
	<blocked dx="1" dy="1" block="true" />
	<blocked dx="1" dy="2" block="true" />
	<blocked dx="0" dy="1" block="true" />
	<blocked dx="0" dy="2" block="true" />
	<blocked dx="-2" dy="0" block="true" />
	<blocked dx="-2" dy="-1" block="true" />
	<blocked dx="-1" dy="-1" block="true" />
	<blocked dx="-1" dy="-2" block="true" />
	<blocked dx="0" dy="-1" block="true" />
	<blocked dx="1" dy="-1" block="true" />
	<blocked dx="1" dy="0" block="true" />
	<blocked dx="0" dy="-2" block="true" />
	<blocked dx="0" dy="0" block="true" />
	<blocked dx="-1" dy="0" block="true" />
	<blocked dx="-2" dy="-2" block="true" />
	<blocked dx="-1" dy="1" block="false" />
	<blocked dx="-3" dy="-1" block="false" />
	<blocked dx="-2" dy="1" block="false" />
	<blocked dx="-1" dy="3" block="false" />
	<blocked dx="-1" dy="2" block="false" />
	<blocked dx="0" dy="4" block="false" />
	<blocked dx="0" dy="3" block="false" />
	<blocked dx="1" dy="4" block="false" />
	<blocked dx="1" dy="3" block="false" />
	<blocked dx="2" dy="4" block="false" />
	<blocked dx="2" dy="3" block="false" />
	<blocked dx="3" dy="4" block="false" />
	<blocked dx="3" dy="3" block="false" />
	<blocked dx="2" dy="2" block="false" />
	<blocked dx="2" dy="1" block="false" />
	<blocked dx="3" dy="2" block="false" />
	<blocked dx="3" dy="1" block="false" />
	<blocked dx="2" dy="0" block="false" />
	<blocked dx="2" dy="-1" block="false" />
	<blocked dx="1" dy="-2" block="false" />
	<blocked dx="0" dy="-3" block="false" />
	<blocked dx="-1" dy="-3" block="false" />
	<blocked dx="-2" dy="-3" block="false" />
	<blocked dx="-3" dy="-2" block="false" />
	<blocked dx="-3" dy="-3" block="false" />
	<door dx="-1" dy="1" />
	<stack dx="2" dy="2" material="CROP" buildrequired="0" />
	<stack dx="0" dy="3" material="PLANK" buildrequired="6" />
	<stack dx="2" dy="3" material="STONE" buildrequired="3" />
	<bricklayer dx="0" dy="3" direction="NORTH_EAST" />
	<bricklayer dx="2" dy="3" direction="NORTH_WEST" />
	<bricklayer dx="3" dy="1" direction="NORTH_WEST" />
	<bricklayer dx="-2" dy="1" direction="NORTH_EAST" />
	<bricklayer dx="-1" dy="2" direction="NORTH_EAST" />
	<bricklayer dx="2" dy="0" direction="NORTH_WEST" />
	<flag dx="-2" dy="-1" />
	<buildmark dx="1" dy="2" />
	<buildmark dx="0" dy="2" />
	<buildmark dx="-2" dy="0" />
	<buildmark dx="-1" dy="-2" />
	<buildmark dx="1" dy="-1" />
	<buildmark dx="-2" dy="-1" />
	<buildmark dx="-2" dy="-2" />
	
	<image file="14" type="GUI" for="GUI" image="0" sequence="15" />

	<startjob name="gohome" />

	<!-- going home job -->
	<job name="gohome" type="GO_TO" successjob="hide" failjob="waithome"
		dx="-1" dy="2" />
	<job name="waithome" type="WAIT" successjob="gohome" failjob="waithome"
		time="3" />
	<job name="hide" type="HIDE" successjob="start" failjob="start" />

	<job name="start" type="WAIT" successjob="checkflour" failjob="show"
		time="3.0" />
	<job name="checkflour" type="NOT_FULL" successjob="checkcrop"
		failjob="hide" dx="-2" dy="1" material="FLOUR" />
	<job name="checkcrop" type="AVAILABLE" successjob="show" failjob="start"
		dx="2" dy="2" material="CROP" />
	<job name="show" type="SHOW" successjob="go_to_crop" failjob="hide"
		dx="-1" dy="2" />
	<job name="go_to_crop" type="GO_TO" successjob="take1" failjob="gohome"
		dx="2" dy="2" />
	<job name="take1" type="DROP" successjob="changeMat1" failjob="gohome"
		material="NO_MATERIAL" />
	<job name="changeMat1" type="SET_MATERIAL" successjob="take2"
		failjob="gohome" material="CROP" />
	<job name="take2" type="TAKE" successjob="go_back" failjob="gohome"
		material="CROP" />
	<job name="go_back" type="GO_TO" successjob="hide1" failjob="gohome"
		dx="-1" dy="2" />
	<job name="hide1" type="HIDE" successjob="makeflour" failjob="start" />
	<job name="makeflour" type="WAIT" successjob="changeMat2" failjob="start"
		time="2.0" />
	<job name="changeMat2" type="SET_MATERIAL" successjob="get_flour"
		failjob="hide" material="FLOUR" />
	<job name="get_flour" type="GO_TO" successjob="look" failjob="gohome"
		dx="-2" dy="1" />
	<job name="look" type="LOOK_AT" successjob="drop" failjob="hide"
		direction="NORTH_EAST" />
	<job name="drop" type="DROP" successjob="changeMat3" failjob="gohome"
		material="FLOUR" />
	<job name="changeMat3" type="SET_MATERIAL" successjob="gohome"
		failjob="gohome" material="NO_MATERIAL" />

</building>

=== AdronTech/settlers-remake/resources/buildings/winegrower.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE building SYSTEM "building.dtd" >
<building worker="">
	<ground groundtype="GRASS" />
	<ground groundtype="EARTH" />
	<ground groundtype="FLATTENED" />

	<blocked dx="1" dy="1" block="true" />
	<blocked dx="2" dy="2" block="true" />
	<blocked dx="1" dy="2" block="true" />
	<blocked dx="0" dy="2" block="true" />
	<blocked dx="0" dy="1" block="true" />
	<blocked dx="-1" dy="1" block="true" />
	<blocked dx="-2" dy="0" block="true" />
	<blocked dx="-1" dy="0" block="true" />
	<blocked dx="0" dy="0" block="true" />
	<blocked dx="1" dy="0" block="true" />
	<blocked dx="2" dy="0" block="true" />
	<blocked dx="1" dy="-2" block="true" />
	<blocked dx="0" dy="-2" block="true" />
	<blocked dx="-1" dy="-2" block="true" />
	<blocked dx="-2" dy="-2" block="true" />
	<blocked dx="-3" dy="-2" block="true" />
	<blocked dx="-3" dy="-4" block="true" />
	<blocked dx="-3" dy="-3" block="true" />
	<blocked dx="-2" dy="-3" block="true" />
	<blocked dx="-2" dy="-4" block="true" />
	<blocked dx="-1" dy="-3" block="true" />
	<blocked dx="0" dy="-3" block="true" />
	<blocked dx="-1" dy="-4" block="true" />
	<blocked dx="2" dy="1" block="true" />
	<blocked dx="-2" dy="1" block="false" />
	<blocked dx="-1" dy="2" block="false" />
	<blocked dx="0" dy="3" block="false" />
	<blocked dx="1" dy="3" block="false" />
	<blocked dx="2" dy="3" block="false" />
	<blocked dx="3" dy="3" block="false" />
	<blocked dx="3" dy="2" block="false" />
	<blocked dx="3" dy="1" block="false" />
	<blocked dx="2" dy="-1" block="false" />
	<blocked dx="1" dy="-3" block="false" />
	<blocked dx="0" dy="-4" block="false" />
	<blocked dx="-1" dy="-5" block="false" />
	<blocked dx="-2" dy="-5" block="false" />
	<blocked dx="-3" dy="-5" block="false" />
	<blocked dx="-4" dy="-5" block="false" />
	<blocked dx="-3" dy="-1" block="false" />
	<blocked dx="-4" dy="-2" block="false" />
	<blocked dx="-3" dy="0" block="false" />
	<blocked dx="-4" dy="-3" block="false" />
	<blocked dx="-4" dy="-4" block="false" />
	<door dx="-1" dy="2" />
	<bricklayer dx="-2" dy="1" direction="NORTH_EAST" />
	<bricklayer dx="0" dy="3" direction="NORTH_EAST" />
	<bricklayer dx="3" dy="3" direction="NORTH_WEST" />
	<bricklayer dx="3" dy="1" direction="NORTH_WEST" />
	<flag dx="-3" dy="-2" />
	<buildmark dx="-2" dy="0" />
	<buildmark dx="0" dy="2" />
	<buildmark dx="2" dy="2" />
	<buildmark dx="2" dy="0" />
	<buildmark dx="-1" dy="-4" />
	<buildmark dx="-3" dy="-4" />
	<buildmark dx="1" dy="-2" />
	
	<image file="14" for="GUI" type="GUI" sequence="90" image="0"/>
</building>

=== AdronTech/settlers-remake/jsettlers.common/resources/buildings/goldmine.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE building SYSTEM "building.dtd" >
<building worker="MINER">
    <ground groundtype="MOUNTAIN" />

    <blocked dx="-2" dy="0" block="true" />
    <blocked dx="-2" dy="-1" block="true" />
    <blocked dx="-1" dy="-1" block="true" />
    <blocked dx="-2" dy="-2" block="true" />
    <blocked dx="-1" dy="1" block="true" />
    <blocked dx="-1" dy="0" block="true" />
    <blocked dx="-1" dy="-2" block="true" />
    <blocked dx="-1" dy="-3" block="true" />
    <blocked dx="0" dy="-2" block="true" />
    <blocked dx="0" dy="-1" block="true" />
    <blocked dx="0" dy="0" block="true" />
    <blocked dx="0" dy="1" block="true" />
    <blocked dx="0" dy="2" block="true" />
    <blocked dx="1" dy="3" block="true" />
    <blocked dx="1" dy="2" block="true" />
    <blocked dx="1" dy="1" block="true" />
    <blocked dx="1" dy="0" block="true" />
    <blocked dx="1" dy="-1" block="true" />
    <blocked dx="2" dy="0" block="true" />
    <blocked dx="2" dy="1" block="true" />
    <blocked dx="-2" dy="1" block="true" />
    <blocked dx="3" dy="2" block="false" />
    <blocked dx="3" dy="3" block="false" />
    <blocked dx="2" dy="2" block="false" />
    <blocked dx="2" dy="3" block="false" />
    <blocked dx="2" dy="4" block="false" />
    <blocked dx="1" dy="4" block="false" />
    <blocked dx="0" dy="3" block="false" />
    <blocked dx="-1" dy="2" block="false" />
    <blocked dx="-3" dy="0" block="false" />
    <blocked dx="-3" dy="-1" block="false" />
    <blocked dx="-3" dy="-2" block="false" />
    <blocked dx="-3" dy="-3" block="false" />
    <blocked dx="-2" dy="-3" block="false" />
    <blocked dx="-2" dy="-4" block="false" />
    <blocked dx="-1" dy="-4" block="false" />
    <blocked dx="0" dy="-3" block="false" />
    <blocked dx="1" dy="-2" block="false" />
    <blocked dx="2" dy="-1" block="false" />
    <blocked dx="3" dy="0" block="false" />
    <blocked dx="3" dy="1" block="false" />
    <blocked dx="4" dy="1" block="false" />
    <blocked dx="4" dy="2" block="false" />
    <blocked dx="4" dy="3" block="false" />
    <blocked dx="-3" dy="1" block="false" />
    <blocked dx="-2" dy="2" block="false" />
    <blocked dx="-1" dy="3" block="false" />
    <blocked dx="0" dy="4" block="false" />
    <door dx="-1" dy="2" />
    <!-- materials checked with original -->
    <constructionStack dx="0" dy="4" material="PLANK" buildrequired="5" />
    <constructionStack dx="2" dy="4" material="STONE" buildrequired="1" />
    <requestStack dx="4" dy="2" material="BREAD" />
    <requestStack dx="3" dy="3" material="MEAT" />
    <requestStack dx="2" dy="4" material="FISH" />
    <bricklayer dx="-2" dy="2" direction="NORTH_EAST" />
    <bricklayer dx="0" dy="3" direction="NORTH_EAST" />
    <bricklayer dx="2" dy="3" direction="NORTH_WEST" />
    <bricklayer dx="3" dy="2" direction="NORTH_WEST" />
    <flag dx="-1" dy="0" />
    <buildmark dx="1" dy="3" />
    <buildmark dx="2" dy="0" />
    <buildmark dx="-1" dy="-3" />
    <buildmark dx="-2" dy="1" />
    <buildmark dx="-2" dy="-2" />

    <image file="14" for="GUI" type="GUI" sequence="48" image="0" />
    <image file="13" for="FINAL" type="SETTLER" sequence="5" image="0" />
    <image file="13" for="BUILD" type="SETTLER" sequence="5" image="1" />

    <!-- going home job -->
    <startjob name="gohome" />
    <job name="gohome" type="GO_TO" successjob="hide" failjob="hide" dx="-1" dy="2" />

    <job name="hide" type="HIDE" successjob="A_wait" failjob="A_wait" />

    <!-- Wait for FISH -->
    <job name="A_wait" type="WAIT" successjob="A_checkore" failjob="A_checkore" time="3" />
    <job name="A_checkore" type="NOT_FULL" successjob="A_checkfood" failjob="B_wait" dx="-1" dy="4" material="GOLDORE" />
    <job name="A_checkfood" type="AVAILABLE" successjob="mine_fish" failjob="B_wait" dx="2" dy="4" material="FISH" />

    <!-- Wait some more for FISH -->
    <job name="B_wait" type="WAIT" successjob="B_checkore" failjob="B_checkore" time="7" />
    <job name="B_checkore" type="NOT_FULL" successjob="C_wait" failjob="C_wait" dx="-1" dy="4" material="GOLDORE" />
    <job name="B_checkfood" type="AVAILABLE" successjob="mine_fish" failjob="C_wait" dx="2" dy="4" material="FISH" />

    <!-- Wait for MEAT -->
    <job name="C_wait" type="WAIT" successjob="C_checkore" failjob="C_checkore" time="10" />
    <job name="C_checkore" type="NOT_FULL" successjob="C_checkfood1" failjob="D_wait" dx="-1" dy="4" material="GOLDORE" />
    <job name="C_checkfood1" type="AVAILABLE" successjob="mine_fish" failjob="C_checkfood2" dx="2" dy="4" material="FISH" />
    <job name="C_checkfood2" type="AVAILABLE" successjob="mine_meat" failjob="D_wait" dx="3" dy="3" material="MEAT" />

    <!-- Wait for BREAD -->
    <job name="D_wait" type="WAIT" successjob="D_checkore" failjob="D_checkore" time="10" />
    <job name="D_checkore" type="NOT_FULL" successjob="D_checkfood1" failjob="E_wait" dx="-1" dy="4" material="GOLDORE" />
    <job name="D_checkfood1" type="AVAILABLE" successjob="mine_fish" failjob="D_checkfood2" dx="2" dy="4" material="FISH" />
    <job name="D_checkfood2" type="AVAILABLE" successjob="mine_meat" failjob="D_checkfood3" dx="3" dy="3" material="MEAT" />
    <job name="D_checkfood3" type="AVAILABLE" successjob="mine_bread" failjob="E_wait" dx="4" dy="2" material="BREAD" />

    <!-- Wait for BREAD -->
    <job name="E_wait" type="WAIT" successjob="E_checkore" failjob="E_checkore" time="10" />
    <job name="E_checkore" type="NOT_FULL" successjob="E_checkfood1" failjob="E_wait" dx="-1" dy="4" material="GOLDORE" />
    <job name="E_checkfood1" type="AVAILABLE" successjob="mine_fish" failjob="E_checkfood2" dx="2" dy="4" material="FISH" />
    <job name="E_checkfood2" type="AVAILABLE" successjob="mine_meat" failjob="E_checkfood3" dx="3" dy="3" material="MEAT" />
    <job name="E_checkfood3" type="AVAILABLE" successjob="mine_bread" failjob="E_wait" dx="4" dy="2" material="BREAD" />

    <job name="mine_meat" type="REMOTETAKE" successjob="mine" failjob="E_wait" material="MEAT" dx="3" dy="3" />
    <job name="mine_bread" type="REMOTETAKE" successjob="mine" failjob="E_wait" material="BREAD" dx="4" dy="2" />
    <job name="mine_fish" type="REMOTETAKE" successjob="mine" failjob="E_wait" material="FISH" dx="2" dy="4" />

    <job name="mine" type="IS_PRODUCTIVE" successjob="successful" failjob="noore1" />

    <!-- successful mining -->
    <job name="successful" type="NOT_FULL" successjob="successfuls" failjob="successfuls" dx="0" dy="4" material="GOLDORE" />
    <job name="successfuls" type="SET_MATERIAL" successjob="show_full" failjob="gohome" material="GOLDORE" />
    <job name="show_full" type="SHOW" successjob="successful1" failjob="gohome" dx="-1" dy="2" />
    <job name="successful1" type="WALK" successjob="successful2" failjob="gohome" direction="SOUTH_WEST" />
    <job name="successful2" type="WALK" successjob="successful3" failjob="gohome" direction="SOUTH_WEST" />
    <job name="successful3" type="LOOK_AT" successjob="successful4" failjob="gohome" direction="SOUTH_WEST" />
    <job name="successful4" type="DROP" successjob="successful7" failjob="gohome" material="GOLDORE" />
    <job name="successful7" type="WALK" successjob="successful8" failjob="gohome" direction="NORTH_EAST" />
    <job name="successful8" type="WALK" successjob="hide" failjob="hide" direction="NORTH_EAST" />

    <!-- failed mining -->
    <job name="noore1" type="SET_MATERIAL" successjob="noore2" failjob="gohome" material="BASKET" />
    <job name="noore2" type="SHOW" successjob="noore4" failjob="gohome" dx="-1" dy="2" />
    <job name="noore4" type="WALK" successjob="noore5" failjob="gohome" direction="SOUTH_WEST" />
    <job name="noore5" type="LOOK_AT" successjob="noore6" failjob="gohome" direction="SOUTH_WEST" />
    <job name="noore6" type="PLAY_ACTION1" successjob="noore7" failjob="gohome" time="5.0" />
    <job name="noore7" type="WALK" successjob="hide" failjob="hide" direction="NORTH_EAST" />
</building>
