=== AdronTech/settlers-remake/jsettlers.mapcreator/src/jsettlers/mapcreator/presetloader/preset.xsd
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="presets">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="preset" maxOccurs="unbounded" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="preset">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="building" maxOccurs="unbounded"
					minOccurs="0" />
				<xs:element ref="object" maxOccurs="unbounded" minOccurs="0" />
				<xs:element ref="moveable" maxOccurs="unbounded"
					minOccurs="0" />
			</xs:sequence>
			<xs:attribute type="xs:string" name="text-id" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="building">
		<xs:complexType>
			<xs:attribute type="xs:int" name="dx" />
			<xs:attribute type="xs:int" name="dy" />
			<xs:attribute type="xs:string" name="type" />
		</xs:complexType>
	</xs:element>

	<xs:element name="object">
		<xs:complexType>
			<xs:attribute type="xs:int" name="dx" />
			<xs:attribute type="xs:int" name="dy" />
			<xs:attribute type="xs:string" name="type" />
			<xs:attribute type="xs:int" name="count" />
		</xs:complexType>
	</xs:element>
	<xs:element name="moveable">
		<xs:complexType>
			<xs:attribute type="xs:int" name="dx" />
			<xs:attribute type="xs:int" name="dy" />
			<xs:attribute type="xs:string" name="type" />
		</xs:complexType>
	</xs:element>

</xs:schema>

=== AdronTech/settlers-remake/jsettlers.mapcreator/src/jsettlers/mapcreator/presetloader/preset.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<presets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="preset.xsd">

	<!-- Name translated in jsettlers.mapcreator.localization -->
	<preset text-id="preset.start">
	</preset>

	<!-- Name translated in jsettlers.mapcreator.localization -->
	<preset text-id="preset-wood">
		<building dx="0" dy="10" type="LUMBERJACK" />
		<building dx="0" dy="0" type="FORESTER" />
		<building dx="3" dy="-9" type="LUMBERJACK" />

		<moveable dx="8" dy="-8" type="LUMBERJACK" />
		<moveable dx="7" dy="3" type="FORESTER" />
		<moveable dx="7" dy="12" type="LUMBERJACK" />
	</preset>
</presets>
